export default [
	{
		adult: false,
		backdrop_path: '/tt79dbOPd9Z9ykEOpvckttgYXwH.jpg',
		belongs_to_collection: null,
		budget: 25000000,
		genres: [
			{
				id: 28,
				name: 'Action',
			},
			{
				id: 12,
				name: 'Abenteuer',
			},
			{
				id: 878,
				name: 'Science Fiction',
			},
		],
		homepage: '',
		id: 545611,
		imdb_id: 'tt6710474',
		original_language: 'en',
		original_title: 'Everything Everywhere All at Once',
		overview:
			'Eine alternde chinesische Einwanderin wird in ein verrücktes Abenteuer hineingezogen, in dem nur sie das retten kann, was ihr wichtig ist, indem sie sich mit den Leben verbindet, die sie in anderen Universen hätte führen können.',
		popularity: 448.322,
		poster_path: '/38LNk3VrCZVE3zQTgqCLwIhiU9u.jpg',
		production_companies: [
			{
				id: 106544,
				logo_path: null,
				name: 'AGBO',
				origin_country: 'US',
			},
			{
				id: 114130,
				logo_path: '/sutv3efLKuB4pa9xxb27paUUcJg.png',
				name: 'Ley Line Entertainment',
				origin_country: 'US',
			},
			{
				id: 161506,
				logo_path: null,
				name: 'Year of the Rat Productions',
				origin_country: '',
			},
			{
				id: 173526,
				logo_path: null,
				name: 'Hotdog Hands LLC',
				origin_country: '',
			},
			{
				id: 41077,
				logo_path: '/1ZXsGaFPgrgS6ZZGS37AqD5uU12.png',
				name: 'A24',
				origin_country: 'US',
			},
			{
				id: 93105,
				logo_path: '/asuzX794BM1gCettTxUoLxGNovd.png',
				name: 'IAC Films',
				origin_country: 'US',
			},
		],
		production_countries: [
			{
				iso_3166_1: 'US',
				name: 'United States of America',
			},
		],
		release_date: '2022-03-24',
		revenue: 114900000,
		runtime: 140,
		spoken_languages: [
			{
				english_name: 'Cantonese',
				iso_639_1: 'cn',
				name: '广州话 / 廣州話',
			},
			{
				english_name: 'Mandarin',
				iso_639_1: 'zh',
				name: '普通话',
			},
			{
				english_name: 'English',
				iso_639_1: 'en',
				name: 'English',
			},
		],
		status: 'Released',
		tagline: 'Das Universum ist so viel größer, als du denkst.',
		title: 'Everything Everywhere All at Once',
		video: false,
		vote_average: 7.903,
		vote_count: 4034,
		similar: {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: '/gOlMx8kFIIUmYVRIKuLbaLhBJSZ.jpg',
					genre_ids: [35, 10751, 14],
					id: 10330,
					original_language: 'en',
					original_title: 'Freaky Friday',
					overview:
						"Dr. Tess Coleman und ihre 15-jährige Tochter Anna kommen nicht gerade gut miteinander aus. Besser gesagt: Sie liegen sich meist in den Haaren. Ärger gibt's um alles. Um die Frisur, die Klamotten, die Musik, die schulischen Leistungen und natürlich die Liebe.  Eines verrückten Freitags sorgen zwei identische chinesische Glückskekse für ein absolutes Chaos: Tess und Anna stellen fest, dass sie sich jeweils im Körper der anderen befinden. Horror! Während Tess sich nun mit fiesen Lehrern, Klausuren und ihrer Musikkarriere rumschlagen muss, frischt Anna das Outfit ihrer Mutter auf, bringt ihre Psychoklienten an den Rand des Nervenzusammenbruchs und Mamis Kreditkarte ans Limit.",
					popularity: 30.392,
					poster_path: '/xoKh2g27h5yJhoJBx9pB1z6s7Io.jpg',
					release_date: '2003-08-05',
					title: 'Freaky Friday - Ein voll verrückter Freitag',
					video: false,
					vote_average: 6.441,
					vote_count: 3304,
				},
				{
					adult: false,
					backdrop_path: '/mwt58ScrmiPUwgkR8NTEA26joMf.jpg',
					genre_ids: [28, 53],
					id: 10348,
					original_language: 'cn',
					original_title: '霹靂火',
					overview:
						'Jackie wird entlassen, weil er heimlich einen unfallsicheren Rennwagen getestet hat. Zurück in Hong Kong hilft er der Polizei, den Drahtzieher illegaler, oft tödlich endender Autorennen, Cougar, zu fassen. Als dieser jedoch entwischt, schwört er Rache und entführt die Schwester von Jackie. Dieser greift daraufhin zur Selbstjustiz…',
					popularity: 35.385,
					poster_path: '/pBjLMyj2Kx3tIz9DvozCwDuYY6K.jpg',
					release_date: '1995-09-08',
					title: 'Thunderbolt',
					video: false,
					vote_average: 6.465,
					vote_count: 254,
				},
				{
					adult: false,
					backdrop_path: '/h5kSM9n8eIec2MzTi2dHIhMbyXP.jpg',
					genre_ids: [9648, 27],
					id: 10349,
					original_language: 'en',
					original_title: 'The Dark Half',
					overview:
						'Thad Beaumont ist ein angesehener College-Professor und seriöser Schrifsteller. Was niemand weiß: Unter dem Pseudonym George Stark verdient er ein Vermögen als Horror-Schriftsteller. Die Romane triefen nur so vor Blut und finden reißenden Absatz. Sein literarisches Doppelleben findet ein jähes Ende, als ein Erpresser droht, Beaumont auffliegen zu lassen. Thad beschließt, sein Alter Ego symbolisch zu Grabe zu tragen und sich nur noch auf die ernsthafte Literatur zu konzentrieren. Als kurz darauf in seiner Umgebung einige Morde verübt werden, wird für ihn ein dunkler Verdacht immer mehr zur Gewissheit: Stark hat sich selbständig gemacht - und benutzt Thad für seine Rachepläne...',
					popularity: 11.301,
					poster_path: '/o0eBmVkvR19TZS1RvxamapnDK2L.jpg',
					release_date: '1993-04-23',
					title: 'Stephen Kings Stark',
					video: false,
					vote_average: 5.992,
					vote_count: 325,
				},
				{
					adult: false,
					backdrop_path: '/8UpJ8svNnwVtpu8n62vGke8MOJf.jpg',
					genre_ids: [12, 16, 10751, 37],
					id: 10380,
					original_language: 'en',
					original_title: 'An American Tail: Fievel Goes West',
					overview:
						'Die Emigranten-Mäuse Mouskewitz müssen feststellen, daß auch in New York die Straßen nicht mit Käse gepflastert sind. So träumt Feivel bereits von der Weite des Westens und sieht sich selbst als Revolverhelden mit Sheriffstern. Die Familie macht sich auf den Weg. Feivel will sein Vorbild, den Sheriff Wylie Burp kennenlernen. Auch Feivels bester Freund Tiger, die freundlichste Katze unter der Sonne, zieht los. Natürlich gehen beide unterwegs verloren, treffen sich in der Wüste wieder, um am Ziel ihrer Träume festzustellen, daß Wylie nicht mehr der ist, von dem die Legenden erzählen, und daß der üble Kater R. Waul längst auch hier das Sagen hat. Da aber sorgt Feivel für Abhilfe.',
					popularity: 20.812,
					poster_path: '/whnaKYmvP1xHvTICAFom4cldqXd.jpg',
					release_date: '1991-11-21',
					title: 'Feivel der Mauswanderer im Wilden Westen',
					video: false,
					vote_average: 6.348,
					vote_count: 638,
				},
				{
					adult: false,
					backdrop_path: '/wTcPEs307cPVYQ6lPXSjQEG416R.jpg',
					genre_ids: [27, 53, 9648],
					id: 10008,
					original_language: 'en',
					original_title: 'An American Haunting',
					overview:
						'Tennessee, im Jahre 1818. Nach einem erbitterten Streit mit einer als Hexe verschrienen Bäuerin liegt plötzlich ein Fluch auf der Familie des Farmers John Bell und seiner Frau Lucy. Eine unsichtbare und unbarmherzige Macht dringt in das Leben der braven Sippe ein, malträtiert besonders Familienoberhaupt John und die halbwüchsige Tochter Betsy. Mit der Zeit wird der Geist immer mächtiger und aggressiver, die Qualen der Bells steigern sich ins Unerträgliche. Ein gespenstischer, blutrünstiger Wolf streift um das Haus, ominöse Stimmen ertönen und schließlich kündigt der paranormale Eindringling an, dass er John Bell töten werde. Während Betsys Verehrer Richard verzweifelt nach einer wissenschaftlichen Erklärung für die Attacken forscht, suchen die Bells ihr Heil in Exorzismen und schließlich in einem dramatischen Fluchtversuch. Doch vor ihrem dämonischen Peiniger scheint es kein Entkommen zu geben. Bis eines Tages das Rätsel des Fluchs gelüftet wird...',
					popularity: 11.756,
					poster_path: '/wkSms9F2kgHAKqstWeFtWMzBHpy.jpg',
					release_date: '2005-05-05',
					title: 'Der Fluch der Betsy Bell',
					video: false,
					vote_average: 5.6,
					vote_count: 419,
				},
				{
					adult: false,
					backdrop_path: '/2OQkSOyC5HuCNpq0XO5EEPEdazX.jpg',
					genre_ids: [35, 10751, 28],
					id: 10022,
					original_language: 'en',
					original_title: 'The Pacifier',
					overview:
						'Der Navy-SEAL Shane Wolfe hat einen Einsatz verbockt, bei dem ein Wissenschaftler ums Leben kam. Zur Strafe muss der Nahkampfspezialist nun dessen Kinder hüten, während ihre Mutter in der Schweiz mit einem US-Beamten ein Schließfach inspiziert, das brisante Geheimnisse enthalten soll. Also befehligt er statt knallharter Soldaten nun fünf rebellische Kids nebst renitentem Kindermädchen. Schnell wünscht sich Wolfe in seinen "normalen" Job zurück, wo Projektile fliegen, Bomben explodieren und das Leben am seidenen Faden hängt.',
					popularity: 28.307,
					poster_path: '/tBJP0rW11zaMsEHZSxjTH0TGyDr.jpg',
					release_date: '2005-03-04',
					title: 'Der Babynator',
					video: false,
					vote_average: 6.051,
					vote_count: 2737,
				},
				{
					adult: false,
					backdrop_path: '/z8ejhyO0hVXk4KVo1bi4HMFP3FS.jpg',
					genre_ids: [28, 80],
					id: 10027,
					original_language: 'en',
					original_title: 'Unleashed',
					overview:
						'Normales menschliches Verhalten ist ein Fremdwort für Danny, einen jungen Mann mit dem Wissenstand und der sozialen Reife eines kleines Kindes. Von seinem "Besitzer" Bart wurde er zur Kampfmaschine gedrillt, muß sich jedoch mit einem Halsband versehen jedoch sonst stets in einem Käfig aufhalten, um für Bart in illegalen Gladiatorenkämpfen mit tödlichem Ausgang anzutreten. Als Bart nach einem schweren Unfall ins Koma verfällt, ist Danny auf einmal auf sich gestellt - und gerät an den blinden Klavierstimmer Sam, der ihn behutsam in die normale Welt einführt und ihm beibringt, was es heißt, ein Mensch zu sein. Nur eines Tages wacht Bart aus seinem Koma wieder auf und will seinen Besitz zurück. Bald steht Danny vor schweren moralischen Entscheidungen...',
					popularity: 24.563,
					poster_path: '/2i0PB4npPEiY1Tj45YbGoTh3suq.jpg',
					release_date: '2005-02-02',
					title: 'Unleashed - Entfesselt',
					video: false,
					vote_average: 6.91,
					vote_count: 1758,
				},
				{
					adult: false,
					backdrop_path: '/iYEw2pvCTOhKUkPQ4U7nX7Zmuav.jpg',
					genre_ids: [28, 35],
					id: 10044,
					original_language: 'cn',
					original_title: '福星高照',
					overview:
						'Der Polizist Muscles aus Hongkong wird nach Tokio geschickt, um dort einen Kollegen zu finden, der sich mit gestohlenen Diamanten abgesetzt hat. Unterstützt wird er von einem Kollegen vor Ort, Ricky. Kurz bevor die beiden zuschlagen können, kommt es zu einer halbrecherischen Verfolgungsjagd mit einer Ninja-Bande, die den Ex-Polizisten  jetzt beschützt. Im Zuge der Auseinandersetzung mit den Ninjas wird Ricky von diesen entführt, weshalb Muscles seine  alte Jugendbande zusammentrommelt, um zusammen mit seinen Freunden Ricky zu befreien und den Anführer der Ninjas zur Strecke zu bringen.',
					popularity: 13.422,
					poster_path: '/kwv8grcspw6KV6YUYbDPm9YaxNh.jpg',
					release_date: '1985-02-10',
					title: 'Tokyo Powerman',
					video: false,
					vote_average: 6.4,
					vote_count: 128,
				},
				{
					adult: false,
					backdrop_path: '/iyUT1zRAvbwScG1sPHqQI7nFwCy.jpg',
					genre_ids: [28, 53, 878],
					id: 10045,
					original_language: 'fr',
					original_title: 'Banlieue 13',
					overview:
						'Im Jahr 2010 ist der 13. Stadtteil von Paris ein riesiges Ghetto, das von einer großen Mauer umgeben ist. Im 13. Banlieue herrscht der Gangsterboss Taha, der die Schwester von Leito entführt hat, weil dieser eine Ladung Koks von ihm vernichtet hat. Leito versucht, sie zu befreien, landet aber im Knast.Der Undercover-Cop Damien bekommt währendessen einen brisanten Auftrag. Eine Neutronenbombe wurde von Taha gestohlen und soll auf Paris abgefeuert werden. Zusammen mit dem ortskundigen Leito soll Damien die Massenvernichtungswaffe wieder zurückholen.',
					popularity: 16.855,
					poster_path: '/6XXe0nK6cK4ujH0rK1u15GaXDBM.jpg',
					release_date: '2004-11-09',
					title: 'Ghettogangz - Die Hölle vor Paris',
					video: false,
					vote_average: 6.755,
					vote_count: 1614,
				},
				{
					adult: false,
					backdrop_path: '/lRyDRKmvenSuej4DbPCM74wrpo5.jpg',
					genre_ids: [28],
					id: 10049,
					original_language: 'en',
					original_title: 'Attack Force',
					overview:
						'Als Marshall Lawson seine Einsatztruppe durch einen kaltblütigen und scheinbar willkürlichen Angriff verliert, macht er es sich zur Aufgabe, die Umstände des brutalen Blutvergießens genauer zu untersuchen. Ziemlich schnell stößt er auf CTX Majestic, eine verdeckte Militäroperation, die so geheim ist, dass das Militär nun Lawson ausschalten will, um das Geheimnis zu schützen. Doch Lawson gibt nicht auf und wird in einen erbarmungslosen Kampf gegen eine Drogenorganisation verstrickt, die allem Anschein nach heimlich von einem kriminellen Arm des Militärs finanziert wird.',
					popularity: 10.532,
					poster_path: '/4uYICyRr94S005YHxDA61WI6P9J.jpg',
					release_date: '2006-12-05',
					title: 'Attack Force',
					video: false,
					vote_average: 4.6,
					vote_count: 84,
				},
				{
					adult: false,
					backdrop_path: '/7v277jmtG4GfZwM7jQdbTV0WqdZ.jpg',
					genre_ids: [28, 12, 878, 53],
					id: 10061,
					original_language: 'en',
					original_title: 'Escape from L.A.',
					overview:
						'Los Angeles wurde überflutet und danach in ein Hochsicherheitsgefängnis umfunktioniert. Da sitzen nicht nur Kriminelle ein, sondern auch politisch unangepasste Menschen. Als nächster eingeliefert werden soll Einzelkämpfer Snake Plissken - aber daraus wird nichts. Utopia, die Tochter des despotischen US-Präsidenten, hat den Prototypen eines Geräts gestohlen, mit dessen Hilfe ein EMP-Signal über die Erde geschickt werden kann, das sämtliche elektrischen Geräte zerstört. Das Gerät hat die abtrünnige Tochter ihrem Geliebten Cuervo Jones übergeben, einer Art moderner Che Guevarra. Die Lage ist klar: Plissken muss da rein, das Teil rausholen, den Möchtegern-Che erledigen und die böse Tochter gleich mit. Damit er sich beeilt, wurde ihm ein Virus eingepflanzt, das ihn innerhalb von zehn Stunden tötet...',
					popularity: 18.858,
					poster_path: '/sHWWG1IrVmiW7YlE3B63Th5UWNZ.jpg',
					release_date: '1996-08-09',
					title: 'Flucht aus L.A.',
					video: false,
					vote_average: 5.852,
					vote_count: 1221,
				},
				{
					adult: false,
					backdrop_path: '/veUujxONO3SyAvfZp5QndqPSzLg.jpg',
					genre_ids: [35, 10751],
					id: 10067,
					original_language: 'en',
					original_title: 'The Shaggy Dog',
					overview:
						'Anwalt Wilby Daniels ist auf dem besten Wege, als Bezirksanwalt vereidigt zu werden – und nimmt dafür auch in Kauf, dass er seine Familie noch mehr vernachlässigen müsste als bisher. Wilby kann nicht ahnen, dass ihm Sonderbares widerfahren wird: Ohne eine Erklärung dafür zu haben, wird er in den ungünstigsten Momenten in einen liebenswerten zotteligen Hund verwandelt. Das erweist sich als denkbar ungünstig für die Karriere und ruft überdies den übereifrigen Hundefänger auf den Plan. Aber das Leben als Hund hat auch etwas Gutes: Mit einem Mal sieht Wilby seine Frau und seine Kinder nicht nur mit ganz anderen Augen – er verliebt sich auch aufs Neue in sie. Aber wie soll er ihnen das klarmachen – als Hund?',
					popularity: 12.337,
					poster_path: '/94d53YITq9IQAbUCODWxGOYi9b7.jpg',
					release_date: '2006-03-09',
					title: 'Shaggy Dog - Hör mal, wer da bellt',
					video: false,
					vote_average: 4.89,
					vote_count: 503,
				},
				{
					adult: false,
					backdrop_path: '/vndouqEyQqpvvk0FwIlkfceblrh.jpg',
					genre_ids: [28, 12, 16, 10751, 35],
					id: 9502,
					original_language: 'en',
					original_title: 'Kung Fu Panda',
					overview:
						'Der kleine Pandabär Po macht in China eine Ausbildung zum Nudelsuppen-Meister. Doch in Wirklichkeit möchte er viel lieber ein berühmter und starker Kung-Fu Kämpfer werden, obwohl sein pummeliges Äußeres und seine Naschsucht vehement dagegen sprechen. Doch Po hat Glück: Eine Prophezeiung sieht vor, dass ein kleiner Bär gegen den gefürchteten Schneeleoparden Tai Lung antreten muss, um das Tal des Friedens zu retten. Es liegt nun an Master Shifu und den fünf Kung-Fu Meistern Tigerin, Kranich, Gottesanbeterin, Viper und Affe den pfundigen Bären zum starken Krieger zu machen.',
					popularity: 84.695,
					poster_path: '/Ao7ikR1ksPyWJT4gcTnCye0VaYY.jpg',
					release_date: '2008-06-04',
					title: 'Kung Fu Panda',
					video: false,
					vote_average: 7.223,
					vote_count: 10086,
				},
				{
					adult: false,
					backdrop_path: '/eerEil7EcnXbtbcwf3lUJpg7O3P.jpg',
					genre_ids: [80, 53, 28],
					id: 9546,
					original_language: 'en',
					original_title: 'Ricochet',
					overview:
						'Bei der Verhaftung des psychopathischen Verbrechers Blake wird der Streifencop Nick Styles von einem Hobbyfilmer auf Video festgehalten und kommt so in die Nachrichten. Während Blake hinter Gitter marschiert, gelingt Styles eine kometenhafte Karriere. Blake glückt die Flucht. Nach allen Regeln der Kunst beginnt er, Styles in der Öffentlichkeit zu diskreditieren. Er dichtet ihm Seitensprünge und Geschlechtskrankheiten an, bringt ihn in Zusammenhang mit Korruption und Drogenhandel und macht ihn schließlich selbst drogenabhängig. Beinahe am Boden zerstört kann sich Styles nur noch auf seine alten Freunde von der Straße verlassen. Mit ihrer Hilfe rechnet er in einem tödlichen Showdown mit Blake ab.',
					popularity: 9.973,
					poster_path: '/5isHYEcUY0nE90uMhkGrs1nnal.jpg',
					release_date: '1991-10-04',
					title: 'Ricochet - Der Aufprall',
					video: false,
					vote_average: 6,
					vote_count: 253,
				},
				{
					adult: false,
					backdrop_path: '/jea4adbYk407PhYK9uhWjihPYAv.jpg',
					genre_ids: [12, 18, 28],
					id: 9550,
					original_language: 'zh',
					original_title: '十面埋伏',
					overview:
						'Visuell-opulentes Action-Drama von "Hero"-Regisseur Zhang Yimou. Im Jahre 859 wird China von der Tang-Dynastie regiert. Doch die Untergrundorganisation "Haus der fliegenden Dolche" will die korrupte Regierung stürzen. Die Polizisten Jin (Takeshi Kaneshiro) und Leo (Andy Lau) versuchen über die blinde Mei (Ziyi Zhang), das Versteck der Rebellen zu finden. Doch Jin verliebt sich in die Rebellin.',
					popularity: 15.837,
					poster_path: '/unwvBq1MjoT1wbVqu8hpIt3B2iZ.jpg',
					release_date: '2004-05-19',
					title: 'House of Flying Daggers',
					video: false,
					vote_average: 7.3,
					vote_count: 1382,
				},
				{
					adult: false,
					backdrop_path: '/2lDo83b3Y5waVB4I8e9WnGU8mbr.jpg',
					genre_ids: [28],
					id: 9569,
					original_language: 'en',
					original_title: 'Hard to Kill',
					overview:
						'Als der Polizist Mason Storm dahinterkommt, dass ein Anschlag auf einen US-Senator geplant wird, ist es bereits zu spät. Aus den eigenen Reihen verraten werden er und seine Familie, sowie einer seiner Kollegen Opfer von Anschlägen. Storm überlebt knapp, fällt aber in ein siebenjähriges Koma. Trotz seiner neuen Identität spricht sich sein Erwachen schnell herum und die Attentäter von damals machen bereits kurze Zeit später erneut Jagd auf ihn. Mithilfe einer Krankenschwester gelingt es ihm jedoch wiederholt zu entkommen. Noch geschwächt von den Folgen des langen Komas beginnt Storm wieder alte Form anzunehmen. Er schwört den Mördern seiner Frau blutige Rache...',
					popularity: 14.514,
					poster_path: '/nmtMNxslljllSTVtt7VIOXdxSZp.jpg',
					release_date: '1990-02-09',
					title: 'Hard to Kill',
					video: false,
					vote_average: 6,
					vote_count: 520,
				},
				{
					adult: false,
					backdrop_path: '/oApE6TUeteedCL3CP1d8pCVfq0X.jpg',
					genre_ids: [12, 35, 10751, 14],
					id: 9259,
					original_language: 'de',
					original_title: 'Bibi Blocksberg',
					overview:
						'In Neustadt herrscht Jubelstimmung: Bibi Blocksberg hat durch eine spontane kleine Hexerei, mit der sie einen kräftigen Regenschauer auslöste, zwei Kinder vor dem sicheren Flammentod bewahrt. Während Mutter Barbara, selbst Hexe aus Fleisch und Blut, mächtig stolz auf ihre Tochter ist, hält der beruflich gestresste Papa Bernhard nur sehr wenig von Bibis übersinnlichen Eskapaden. Da erhält Bibi von Oberhexe Walpurgia die Nachricht, dass ihr aufgrund besonderer Verdienste bereits vorzeitig die “Kristallkugel”, die sie erst zur richtigen Hexe macht, verliehen wird. Voller Stolz fliegt Bibi mit ihrem Besen, der auf den Namen “Kartoffelbrei” hört, auf den Blocksberg. Doch die verschlagene Rabia  eine der bösen Hexen, gönnt der Junghexe die hohe Ehre nicht. Noch am Blocksberg schwört sie erst zu ruhen, wenn sie Bibi die kostbare Kugel wieder abgejagt hat.',
					popularity: 8.317,
					poster_path: '/9r7epbLqqtjtlkvRpCwVHIiGkB.jpg',
					release_date: '2002-09-25',
					title: 'Bibi Blocksberg',
					video: false,
					vote_average: 6,
					vote_count: 71,
				},
				{
					adult: false,
					backdrop_path: '/v9myBXtpmsSzOtI1go3UofRkTiK.jpg',
					genre_ids: [35, 10751],
					id: 9284,
					original_language: 'de',
					original_title: 'Rennschwein Rudi Rüssel',
					overview:
						'Rudi, seines Zeichens Glücksbringer und erster Preis einer Feuerwehrfest-Verlosung, mischt die Familie des arbeitslosen Ägyptologen Heinrich Gützkow auf. Kaum im Haus der sympathischen Familie eingetroffen, wird diese vom Vermieter auf die Straße gesetzt: Hier darf kein Schwein rein! Der örtliche Fussballverein stiftet ein neues Zuhause und einen Arbeitsplatz für den Vater. Herr Gützkow wird Platzwart, und Rudi rennt mit den Fussballern um die Wette. Außerdem beißt er den Schiedsrichter ins Bein. Die Familie verzweifelt immer mehr, doch Rudi macht erst mal Rennschwein-Karriere! Als der wieselflinke Renner schließlich irrtümlich in den Schlachthof transportiert wird, beginnt eine dramatische Rettungsaktion...',
					popularity: 1.404,
					poster_path: '/cTC8wSdwIsDjypjYDEIvKZlKA7b.jpg',
					release_date: '1995-01-01',
					title: 'Rennschwein Rudi Rüssel',
					video: false,
					vote_average: 5.7,
					vote_count: 12,
				},
				{
					adult: false,
					backdrop_path: '/YZVX4nqC9pwdDmRr2euKkGlOum.jpg',
					genre_ids: [37, 35],
					id: 9287,
					original_language: 'it',
					original_title: 'Botte di Natale',
					overview:
						'Der raffinierte Fäustling und der schwere Brummer – das perfekte Duo für eine aberwitzige Westernkomödie. Travis und Moses, zwei ungleiche Brüder, erhalten nach zwanzig Jahren erstmals wieder Post von ihrer alten Mutter, die ihre beiden Söhne noch einmal sehen möchte und ihnen Vaters Erbschaft aushändigen will. Berufsspieler Travis macht sich sofort auf den Weg, doch der behäbige Kopfgeldjäger Moses liegt mit der ganzen Familie im Streit und jagt lieber den Banditen Stone. Doch der Wunsch ihrer alten Mutter, sie mögen sich doch endlich wieder versöhnen, veranlasst die beiden schlitzohrigen Brüder, wenigstens guten Willen zu zeigen – aber da grinst das Chaos schon aus allen Ritzen.',
					popularity: 11.212,
					poster_path: '/s0DTANyksnem9yJsQXwMYET8ah4.jpg',
					release_date: '1994-11-25',
					title: 'Die Troublemaker',
					video: false,
					vote_average: 6.107,
					vote_count: 187,
				},
				{
					adult: false,
					backdrop_path: '/18TnrNODUgYaV3URw6VB4v6KRyo.jpg',
					genre_ids: [878, 28, 53],
					id: 8202,
					original_language: 'en',
					original_title: 'Æon Flux',
					overview:
						'400 Jahre in der Zukunft, genauer im Jahre 2415, ist Æon Flux eine mysteriöse Attentäterin. Vier Jahrhunderte nach einem Virus, der fast die gesamte menschliche Rasse ausgelöscht hat, leben 5 Millionen Menschen in einer utopischen Stadt genannt Bregna. Æon kämpft um das Goodchild Regime zu vernichten, dass von ihrem Namensvetter und Herrschers von Bregna, Trevor Goodchild angeführt wird. Æon versucht Trevor Goodchild zu töten, doch kurz bevor offenbaren sich weitere Geheimnisse die entdeckt werden müssen und Verschwörungen die vereitelt werden müssen.',
					popularity: 17.224,
					poster_path: '/eqqV7NmGBGej7EfCdyStg4YpXa9.jpg',
					release_date: '2005-11-30',
					title: 'Æon Flux',
					video: false,
					vote_average: 5.596,
					vote_count: 1942,
				},
			],
			total_pages: 254,
			total_results: 5080,
		},
	},
	{
		adult: false,
		backdrop_path: '/4avmIRBBOs9b4DKoenf8SWWJJP7.jpg',
		belongs_to_collection: null,
		budget: 0,
		genres: [
			{
				id: 18,
				name: 'Drama',
			},
			{
				id: 36,
				name: 'Historie',
			},
		],
		homepage: '',
		id: 726759,
		imdb_id: 'tt12758060',
		original_language: 'en',
		original_title: 'Tetris',
		overview: '',
		popularity: 17.532,
		poster_path: '/4F2QwCOYHJJjecSvdOjStuVLkpu.jpg',
		production_companies: [
			{
				id: 5374,
				logo_path: '/pMUiImmYANjZUlZFiZMWziQDSs6.png',
				name: 'Marv Films',
				origin_country: 'GB',
			},
			{
				id: 51860,
				logo_path: null,
				name: 'AI Film',
				origin_country: 'GB',
			},
			{
				id: 60323,
				logo_path: '/6IzmhiRMaYUxORjiJ5vZm9gSagy.png',
				name: 'Unigram',
				origin_country: 'GB',
			},
		],
		production_countries: [
			{
				iso_3166_1: 'GB',
				name: 'United Kingdom',
			},
		],
		release_date: '2023-03-15',
		revenue: 0,
		runtime: 117,
		spoken_languages: [
			{
				english_name: 'English',
				iso_639_1: 'en',
				name: 'English',
			},
			{
				english_name: 'Russian',
				iso_639_1: 'ru',
				name: 'Pусский',
			},
		],
		status: 'Released',
		tagline: '',
		title: 'Tetris',
		video: false,
		vote_average: 4.5,
		vote_count: 2,
		recommendations: {
			page: 1,
			results: [],
			total_pages: 0,
			total_results: 0,
		},
		similar: {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: '/cFGE7Bx9ur6nAuc5v4x9If99Ugy.jpg',
					genre_ids: [80, 18],
					id: 226,
					original_language: 'en',
					original_title: "Boys Don't Cry",
					overview:
						'Brandon Teena, ein junger Transsexueller, geboren als Teena Renae Brandon, ist äußerlich eine junge Frau. Seinem Geschlechts- und Körperempfinden als Mann folgend, kleidet er sich männlich, um die gefühlte Identität auszuleben. Unter männlichem Namen verlässt er seinen Heimatort, um in der US-amerikanischen Provinz ein neues Leben zu beginnen. In einem kleinen Ort freundet er sich mit einer jugendlichen Clique an, John, Tom, Candace, Kate und Lana. Bald darauf ist er in der Clique akzeptiert und verliebt sich in Lana.',
					popularity: 12.945,
					poster_path: '/2ySjUoEZYYiP27LScFTJLu8mYEV.jpg',
					release_date: '1999-09-02',
					title: "Boys Don't Cry",
					video: false,
					vote_average: 7.448,
					vote_count: 1148,
				},
				{
					adult: false,
					backdrop_path: '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
					genre_ids: [18, 36, 10752],
					id: 424,
					original_language: 'en',
					original_title: "Schindler's List",
					overview:
						'Von einer wahren Begebenheit inspiriert, erzählt Schindlers Liste die Geschichte des Industriellen Oskar Schindler, der während des Zweiten Weltkriegs versucht, sich in Krakau eine Existenz aufzubauen. Aus finanziellen Gründen beschäftigt er nur Juden und leiht sich Geld von ihnen um eine Emaillefabrik zu gründen, die ihm letztlich großen Reichtum beschert. Als die Brutalität des Holocaust Krakau erreicht, riskiert er nicht nur sein Vermögen, sondern auch sein Leben um seine Arbeiter vor der Deportation zu bewahren.',
					popularity: 50.098,
					poster_path: '/6lzgetyAEL6rKzeac7r9X7lRVkA.jpg',
					release_date: '1993-12-15',
					title: 'Schindlers Liste',
					video: false,
					vote_average: 8.568,
					vote_count: 13886,
				},
				{
					adult: false,
					backdrop_path: '/msCHK5Kh1YbdZ0zPJ2nzPUhhSN9.jpg',
					genre_ids: [14, 18, 9648],
					id: 141,
					original_language: 'en',
					original_title: 'Donnie Darko',
					overview:
						'Auf den ersten Blick könnte Donnie Darko ein normaler, unkomplizierter Teenager sein. Geordnete Familienverhältnisse, verständnisvolle Eltern, eine nette Freundin. Aber Donnie hat ein mentales Problem – ein drei Meter großes, ziemlich dämonisches Kaninchen namens Frank. Nachts, wenn alles schläft, spricht seine sonore Stimme zu ihm und erteilt ihm Ratschläge. Die sind manchmal hilfreich und manchmal nicht, bezüglich jedweder Zukunftsprognose aber grundsätzlich zutreffend. Die von Donnies Eltern beauftragte Diplompsychologin ist genauso ratlos wie der schuleigene Motivationstrainer oder die freundliche Klassenlehrerin. Als Frank Donnie erklärt, dass in ziemlich genau 28 Tagen, 6 Stunden, 42 Minuten und 12 Sekunden die Welt untergeht, ist guter Rat mal wirklich teuer.',
					popularity: 39.53,
					poster_path: '/yPtjm9QVsXLMsrYFEFZGzdXqsbz.jpg',
					release_date: '2001-10-24',
					title: 'Donnie Darko',
					video: false,
					vote_average: 7.783,
					vote_count: 11089,
				},
				{
					adult: false,
					backdrop_path: '/gE0MLnPzXHoAJIogLhsqt0RW39R.jpg',
					genre_ids: [12, 35, 18, 10751],
					id: 183,
					original_language: 'en',
					original_title: 'The Wizard',
					overview:
						'Er ist erst sechs Jahre und schon der absolute Computerspiele-Crack. Er haut ab nach Los Angeles, um bei der Endausscheidung des Nintendo-Finales mitzumachen. Verfolgt von einem Kopfgeldjäger und seinen Eltern, schafft es Jimmy in letzter Minute dort mitzumischen. Nichts ist dem Einstein-Knirps kompliziert genug: Von Shoot’em Up und Beat’em Up über Jump &amp; Run zu Adventure oder Point &amp; Click mit Levels von höchstem Schwierigkeitsgrad. Den Top High-Score erreicht der Ausreißer immer. Doch jetzt muß Jimmy ein Spiel gewinnen, das bislang unter Geheimverschluß lag. Sein Gegner ist ein hinterhältiger Zocker, der den interactiven Wahnsinn verdammt gut beherrscht.',
					popularity: 10.029,
					poster_path: '/bctDSh4uaiTSSMAhs3V7hwlVjqM.jpg',
					release_date: '1989-12-15',
					title: 'Joy Stick Heroes',
					video: false,
					vote_average: 6.008,
					vote_count: 263,
				},
				{
					adult: false,
					backdrop_path: '/vXhTr0cN54R0TbSD9iG5cuAEWcT.jpg',
					genre_ids: [28, 18, 36, 10752],
					id: 197,
					original_language: 'en',
					original_title: 'Braveheart',
					overview:
						'Ende des 13. Jahrhunderts ermorden britische Besatzer die geliebte Frau des in Schottland lebenden William Wallace. Von dieser Tat aufgestachelt und blind vor Rache, mobilisiert er seine schottischen Landleute für einen Feldzug gegen die übermächtigen Engländer. Trotz ihrer nicht nur zahlenmäßigen Unterlegenheit schafft man das Unfassbare und besiegt die Armee des britischen Königs. Nach dem Sieg stehen jedoch nicht alle Schotten hinter Wallace und verraten ihren Freiheitskämpfer.',
					popularity: 48.824,
					poster_path: '/5MiqFuwgBrvIF3KJ6nWaqUeAe52.jpg',
					release_date: '1995-05-24',
					title: 'Braveheart',
					video: false,
					vote_average: 7.932,
					vote_count: 8983,
				},
				{
					adult: false,
					backdrop_path: '/syO4HCR4t3tz6TX9CbYlW9fTQX3.jpg',
					genre_ids: [18, 80, 53],
					id: 2001,
					original_language: 'en',
					original_title: 'We Own the Night',
					overview:
						'Ein Mann. Zwei Welten. Eine Entscheidung. Sex, Drogen und Alkohol – für den New Yorker Nachtclub-Manager Bobby Green und seine Freundin Amanda ist das Leben eine einzige Party. Bobby träumt davon, eines Tages seinen eigenen Club zu besitzen. Dafür drückt er beide Augen zu, wenn die Russen-Mafia den Club für Drogengeschäfte nutzt. Und nur Amanda weiß, dass sein Vater und sein Bruder Joseph erfolgreiche Polizisten sind. Nach einem Mordanschlag auf Joseph steht Bobby zwischen den Fronten eines Drogenkriegs und muss sich entscheiden: Bringt er gemeinsam mit seinem Vater die brutalen Attentäter zur Strecke oder wird er Mitglied im größten Mafiaring, den es in New York je gab?',
					popularity: 12.441,
					poster_path: '/zCCPxxrPLCcw8LLxRS7hT0nfaPy.jpg',
					release_date: '2007-10-12',
					title: 'Helden der Nacht',
					video: false,
					vote_average: 6.689,
					vote_count: 1168,
				},
				{
					adult: false,
					backdrop_path: '/vseQJJ78NzjNNqfSji4xNlt8HBy.jpg',
					genre_ids: [18],
					id: 2007,
					original_language: 'en',
					original_title: "Lorenzo's Oil",
					overview:
						'Als Augusto und Michaela Odone erfahren, dass ihr fünfjähriger Sohn an einer seltenen und tödlichen Krankheit leidet, beginnt für die beiden eine ungewöhnliche Mission. Trotz der negativen Prognose machen sich die Odones auf, ihr Kind zu retten. Sie müssen sich mit Ärzten, Wissenschaftlern und Hilfsorganisationen anlegen, die dem Paar wenig Unterstützung bei ihrer Suche nach einem Heilmittel bieten. Ihr unermüdlicher Einsatz wird zur Beweisprobe für ihre Ehe, ihre Überzeugungen und die Grenzen herkömmlicher Medizin.',
					popularity: 15.369,
					poster_path: '/e1qabu8H8yAUZz4QrGGGI4kTRR5.jpg',
					release_date: '1992-12-30',
					title: 'Lorenzos Öl',
					video: false,
					vote_average: 7.054,
					vote_count: 459,
				},
				{
					adult: false,
					backdrop_path: '/c59jI0WaKoIffuoLG8iB8L4Z9xM.jpg',
					genre_ids: [18],
					id: 2009,
					original_language: 'ro',
					original_title: '4 luni, 3 săptămîni și 2 zile',
					overview:
						'In einem grauen, entsetzlich trostlosen Studentenwohnheim teilen die beiden Freundinnen Otilia und Gabita ihr kärgliches Zimmer. Als Gabita ungewollt schwanger wird, steht sie vor einem Problem, aus dem es scheinbar keinen Ausweg gibt, denn Abtreibungen stehen unter strenger Strafe. Doch gemeinsam mit ihrer Freundin lehnt Gabita sich gegen das unerbittliche Regime auf. Sie leihen sich Geld und machen einen Abtreibungsarzt ausfindig. Allerdings erweist sich Bebe als echtes Problem, denn als er feststellt, das Gabitas Schwangerschaft schon viel weiter fortgeschritten ist als zunächst angenommen, demütigt er die beiden jungen Frauen und fordert nicht nur mehr Geld sondern auch Sex als Belohnung seiner Dienste. Es beginnt eine quälende und erniedrigende Tortur und die beiden Frauen schlittern in ein heilloses Fiasko …',
					popularity: 8.408,
					poster_path: '/x8GbcJ8U3CTZV05AUydERiJCiCX.jpg',
					release_date: '2007-08-24',
					title: '4 Monate, 3 Wochen und 2 Tage',
					video: false,
					vote_average: 7.533,
					vote_count: 614,
				},
				{
					adult: false,
					backdrop_path: '/29t7THr2KxAHcCrtd1yxaaNW3g9.jpg',
					genre_ids: [28, 80, 18, 9648, 53],
					id: 2017,
					original_language: 'en',
					original_title: 'No Good Deed',
					overview:
						'Jack soll das Verschwinden eines 15-jährigen Mädchens aufklären. Bei seinen Nachforschungen stört er eine Gangsterbande bei der Vorbereitung eines millionenschweren Coups. In der Gewalt der Gangster erkennt Jack schnell, dass innerhalb der Gruppe Spannungen entstehen und sich Fronten bilden. Tyron, der Kopf der Bande, hält die subtile Erin für sein Eigentum, während der naive Hoop das ganz anders sieht. Als schließlich der Coup anläuft, verstrickt sich die Bande in Intrigen und Verdächtigungen.',
					popularity: 10.31,
					poster_path: '/7XozaxWNTC7LqLmeGnt7j6Htb2v.jpg',
					release_date: '2002-06-28',
					title: 'No Good Deed',
					video: false,
					vote_average: 5.404,
					vote_count: 146,
				},
				{
					adult: false,
					backdrop_path: '/jSHHUHRcShP6DJbg0H2lO4A8m9x.jpg',
					genre_ids: [18, 36, 10752, 28],
					id: 2024,
					original_language: 'en',
					original_title: 'The Patriot',
					overview:
						'Ende des 18. Jahrhunderts, South Carolina, USA. Benjamin Martin hat sich zurückgezogen und kümmert sich nach den Tagen als Kriegsheld nur noch um sein Gut und seine Familie. Die Engländer dringen als Kolonialmacht vor und gefährden seinen Besitz, sein ältester Sohn stirbt und sein Haus wird niedergerissen. Martin möchte jedoch nur Frieden, erkennt aber relativ schnell, dass er seine Existenz samt Familie nur dann beschützen kann, wenn er gegen die Engländer zu den Waffen greift...',
					popularity: 33.257,
					poster_path: '/1iXMmBZ0X98J8JYEeuwxXT0SaPK.jpg',
					release_date: '2000-06-28',
					title: 'Der Patriot',
					video: false,
					vote_average: 7.16,
					vote_count: 3383,
				},
				{
					adult: false,
					backdrop_path: '/eJ1UkFvKCQUqVW5lswBMYMRKn4Q.jpg',
					genre_ids: [28, 80, 53],
					id: 2099,
					original_language: 'en',
					original_title: 'Raw Deal',
					overview:
						'Brutal wird Chicago von der Mafia kontrolliert. Als bei einem hinterhältigen Mordanschlag FBI Agenten abgeknallt werden, holt sich der Chef des Bundeskriminalamtes seinen kaltblütigsten Mann - Kaminski. Als Gangster getarnt, schleust sich der Einzelkämpfer in die Organisation ein. Die größte Gefahr für ihn ist die verführerische Monique, die als Spitzel für das Mörderkommando arbeitet.',
					popularity: 15.49,
					poster_path: '/kqEgSdfZgGcZoYXLDARDHtoZfty.jpg',
					release_date: '1986-06-06',
					title: 'Der City Hai',
					video: false,
					vote_average: 5.803,
					vote_count: 664,
				},
				{
					adult: false,
					backdrop_path: '/t2DJFqKeoXwxkexpDyFtrNKcwlP.jpg',
					genre_ids: [80, 18],
					id: 1807,
					original_language: 'en',
					original_title: 'Elephant',
					overview:
						'In einer Highschool in einer US-Kleinstadt geht alles seinen normalen Gang. Die Gesprächsthemen sind wie immer, der Unterricht ist wie immer und Schüler und Lehrer sind wie immer. Nichts deutet darauf hin, dass die Normalität dieses Tages schon bald Geschichte sein wird. Denn an diesem Tag wird für die Schüler und Lehrer der Highschool das Gefühl der Sicherheit zusammenbrechen, das ihnen die ständige Routine vermittelt. Die Banalität des Alltags weicht einer grausamen Tat, die von den Tätern aber mit der gleichen ruhigen Routine durchgeführt wird, wie der Tag begonnen hat. Die beiden Schüler Alex und Eric dringen mit einem Arsenal aus unterschiedlichen Waffen, das sie in einer Sporttasche mit sich führen, in die Schule ein. Sie verüben ein blutiges Massaker und erschießen alle, die ihnen über den Weg laufen...',
					popularity: 22.166,
					poster_path: '/1a4VU9z2hxEvugHMK7VsobB9xTX.jpg',
					release_date: '2003-09-20',
					title: 'Elephant',
					video: false,
					vote_average: 7.097,
					vote_count: 1627,
				},
				{
					adult: false,
					backdrop_path: '/zUs2GW4rPSIsfzBp0GtXaQR2mqk.jpg',
					genre_ids: [18, 10402],
					id: 1808,
					original_language: 'en',
					original_title: 'Velvet Goldmine',
					overview:
						'Auf der Höhe seines Ruhms täuscht Brian Slade, der unangefochtene König des Glam Rock, seine eigene Ermordung vor und verschwindet spurlos. Zehn Jahre später soll der Journalist Arthur Stuart die Hintergründe des Popskandals aufhellen. Ein Rückblick auf die 70er Jahre und ihre Pop-Ikonen.',
					popularity: 13.054,
					poster_path: '/gSbfSGT23CNr5ISIIPAksot074y.jpg',
					release_date: '1998-10-23',
					title: 'Velvet Goldmine',
					video: false,
					vote_average: 6.941,
					vote_count: 422,
				},
				{
					adult: false,
					backdrop_path: '/eTlGkHmrLbztb8gA7R7FpOZ9ewD.jpg',
					genre_ids: [80, 18],
					id: 1623,
					original_language: 'en',
					original_title: 'Brubaker',
					overview:
						'Anstatt seine neue Stelle als Gefängnisdirektor ordnungsgemäß anzutreten, geht Henry Brubaker erst mal einige Wochen als Häftling in die eigene Anstalt. Dort erlebt er den Klüngel und die Korruption, die mit den Gefangenen getrieben werden, am eigenen Leib. Als er sich dann enttarnt, beginnt ein harter Kampf gegen die Korruption und die Behinderung gegen die örtlichen Stellen.  Doch dann entdeckt Brubaker noch Ungeheueres: auf dem Gelände des Gefängnisses sind Leichen vergraben ...',
					popularity: 8.813,
					poster_path: '/r4rYu81u0Hmww8ybp7f5i8Oy9kJ.jpg',
					release_date: '1980-06-20',
					title: 'Brubaker',
					video: false,
					vote_average: 7.063,
					vote_count: 391,
				},
				{
					adult: false,
					backdrop_path: '/n7zm7vcZ5m2nSV9Scyh2axpY8d4.jpg',
					genre_ids: [80, 18],
					id: 1646,
					original_language: 'en',
					original_title: 'Freedom Writers',
					overview:
						'Die angehende weiße Lehrerin Erin Gruwell bekommt eine Anstellung an der Wilson Highschool in Long Beach. Sie soll einen Englischkurs mit von der Schulleitung längst abgeschriebenen Problemkindern ausländischer Herkunft unterrichten, deren Alltag aus Gewalt, Rassismus und Drogen besteht. So hat Erin es am Anfang nicht leicht, sich gegen die jungen Wilden durchzusetzen, doch nach und nach gewinnt sie den Respekt der Kinder und schafft es, die Klasse von ihrer Perspektivlosigkeit zu befreien.',
					popularity: 21.869,
					poster_path: '/81AdeUQT99N0xPg3j6RVh0YGOTk.jpg',
					release_date: '2007-01-05',
					title: 'Freedom Writers',
					video: false,
					vote_average: 7.923,
					vote_count: 1932,
				},
				{
					adult: false,
					backdrop_path: '/5jCpCFrku6wmCZOYZWhHOC2j8IU.jpg',
					genre_ids: [28, 12, 53],
					id: 1669,
					original_language: 'en',
					original_title: 'The Hunt for Red October',
					overview:
						'Der russische Kommandant Ramius setzt sich samt Mannschaft mit seinem dank neuer Antriebssysteme nahezu unortbaren Atom-U-Boot "Roter Oktober" in Richtung Westen ab. Einem US-U-Boot gelingt es, die "Roter Oktober" zu orten. Der Krisenstab befürchtet, Ramius plane auf eigene Faust einen Angriff auf die USA. Nur CIA-Agent Jack Ryan glaubt, dass es sich bei Ramius um einen Überläufer handelt. Er geht an Bord des US-U-Boots und nimmt Kontakt mit Ramius auf, der sich als Überläufer entpuppt, seine Mannschaft aber im Glauben gelassen hat, ihr Einsatz sei ein Angriff. Mit vereinten Kräften gilt es nun, die Attacke eines russischen U-Boots abzuwehren.',
					popularity: 25.068,
					poster_path: '/4sVVRZ343Y9udgmN0QZBj5QVTin.jpg',
					release_date: '1990-03-02',
					title: 'Jagd auf Roter Oktober',
					video: false,
					vote_average: 7.388,
					vote_count: 2812,
				},
				{
					adult: false,
					backdrop_path: '/nKOQiWjhv6LXXSR3PiIab3LrKtU.jpg',
					genre_ids: [18],
					id: 1402,
					original_language: 'en',
					original_title: 'The Pursuit of Happyness',
					overview:
						'San Francisco in den 80ern. Chris Gardner ist ein aufgeweckter und talentierter Verkäufer, der sich von Job zu Job hangelt. Er kämpft ständig darum, finanziell über die Runden zu kommen. Als er eines Tages sein Apartment räumen muss, steht er mit seinem fünfjährigen Sohn Christopher buchstäblich auf der Straße und weiß nicht mehr wo hin. Er und sein Sohn müssen harte Zeiten überstehen, bis es Gardner gelingt, ein Praktikum bei einer namhaften Maklerfirma zu ergattern. Fest entschlossen, seinen Traum von einem besseren Leben zu verwirklichen, schlägt sich Gardner zunächst in Obdachlosenasylen durch, ehe sein persönliches Streben nach Glück von Erfolg gekrönt ist...',
					popularity: 46.745,
					poster_path: '/sXZtUH2DBRyTtphO78O5hdM1snn.jpg',
					release_date: '2006-12-14',
					title: 'Das Streben nach Glück',
					video: false,
					vote_average: 7.902,
					vote_count: 8842,
				},
				{
					adult: false,
					backdrop_path: '/jRJ0CSlpzO4Y0pTiXAcwdTS38gu.jpg',
					genre_ids: [18, 10749, 36],
					id: 1439,
					original_language: 'en',
					original_title: 'Anna and the King',
					overview:
						'Im Jahre 1862 wird Anna Leonowens, eine verwitwete britsche Gouvernante, von König Mongkut von Siam damit beauftragt, dessen gut 50-köpfige Kinderschar zu unterrichten. Nach dem anfängliche Vorurteile zwischen dem östlichen Herrscher und seiner westlichen Angestellten abgebaut sind, wachsen aus erstem Misstrauen Respekt und Zuneigung. Als umstürzlerische Generäle und britische Kolonialherren den Herrscher von Siam und sein Land bedrohen, wird beiden sehr bald klar, dass ihre Liebe keine Zukunft haben kann.',
					popularity: 10.788,
					poster_path: '/obMi5eq43x7gVBwtzk2GI51WHXM.jpg',
					release_date: '1999-12-16',
					title: 'Anna und der König',
					video: false,
					vote_average: 6.8,
					vote_count: 667,
				},
				{
					adult: false,
					backdrop_path: '/bneUTWFAcVCdsb0O5UwZbJd8xqZ.jpg',
					genre_ids: [53, 18, 80],
					id: 1359,
					original_language: 'en',
					original_title: 'American Psycho',
					overview:
						'Auf den ersten Blick ist Patrick Bateman ein stinknormaler, egomanischer Wall-Street-Yuppie, doch hinter der Fassade des proper gewandten Lebemannes verbirgt sich ein mörderischer Abgrund aus Hass und Sadismus. Um die Leere seines einzig von Statussymbolen erhellten Daseins auszufüllen, ist Patrick auf den Serienmord gekommen, insbesondere junge Frauen, aber auch der eine oder andere unvorsichtige Geschäftspartner zählen zu seinen Opfern. Als es ihm zunehmend schwerfällt, zwischen Phantasie und Realität zu unterscheiden, tritt die Polizei auf den Plan.',
					popularity: 54.411,
					poster_path: '/26K6r3s3pjzU1yg2V3HtZ8eCEtg.jpg',
					release_date: '2000-04-13',
					title: 'American Psycho',
					video: false,
					vote_average: 7.392,
					vote_count: 9137,
				},
				{
					adult: false,
					backdrop_path: '/rFas9NuL5VPezt48JirQR0V2y7t.jpg',
					genre_ids: [80, 18, 53],
					id: 1830,
					original_language: 'en',
					original_title: 'Lord of War',
					overview:
						'Der Handel mit Waffen ist ein dreckiges aber lukratives Geschäft. Und Yuri Orlov ist darin der Beste. Nach bescheidenen Anfängen in New Yorks Stadtteil Little Odessa steigt er gemeinsam mit seinem Bruder Vitali nach dem Fall des Eisernen Vorhangs zum mächtigsten Waffenschieber der Welt auf. Unmenschliche Diktatoren und legitime Staatsoberhäupter – Yuri versorgt sie alle. Partei ergreift er nicht, so lange die Kasse stimmt. Da heftet sich auf dem Höhepunkt seiner Karriere der Interpol-Agent Jack Valentine an seine Fersen und Ehefrau Ava stellt ihn vor ein Ultimatum. Yuri will sich für die Familie entscheiden, doch seine Kunden sind ihm unangenehm treu…',
					popularity: 25.073,
					poster_path: '/mh4gWG6ZkHxqbHqgubbakAPI50J.jpg',
					release_date: '2005-09-16',
					title: 'Lord of War - Händler des Todes',
					video: false,
					vote_average: 7.268,
					vote_count: 4061,
				},
			],
			total_pages: 129,
			total_results: 2580,
		},
	},
	{
		adult: false,
		backdrop_path: '/rfkIeCaIHhN3K5wjJJqKmfUjYp8.jpg',
		belongs_to_collection: null,
		budget: 25000000,
		genres: [
			{
				id: 18,
				name: 'Drama',
			},
			{
				id: 36,
				name: 'Historie',
			},
		],
		homepage: '',
		id: 381284,
		imdb_id: 'tt4846340',
		original_language: 'en',
		original_title: 'Hidden Figures',
		overview:
			'Hidden Figures ist die unglaubliche, noch nie erzählte Geschichte von Katherine Johnson, Dorothy Vaughan und Mary Jackson. – Herausragende afro-amerikanische Frauen, die bei der NASA gearbeitet haben und in dieser Funktion als brillante Köpfe einer der größten Unternehmungen in der Geschichte gelten: Sie haben den Astronauten John Glenn in die Umlaufbahn geschickt. – Eine fantastische Errungenschaft, die der Nation neues Selbstbewusstsein gab, das Rennen im Weltall neu definierte und die Welt aufrüttelte. Dieses visionäre Trio überschritt jegliche Geschlechts- und Rassengrenzen und inspirierte Generationen, an ihren großen Träumen festzuhalten.',
		popularity: 62.348,
		poster_path: '/5vcKIRgaGI2IBXCid0M5TqABnrd.jpg',
		production_companies: [
			{
				id: 711,
				logo_path: '/tEiIH5QesdheJmDAqQwvtN60727.png',
				name: 'Fox 2000 Pictures',
				origin_country: 'US',
			},
			{
				id: 83024,
				logo_path: null,
				name: 'Levantine Films',
				origin_country: 'US',
			},
			{
				id: 7076,
				logo_path: '/8BFxn9NUWSgp0ndih569Gm62xiC.png',
				name: 'Chernin Entertainment',
				origin_country: 'US',
			},
		],
		production_countries: [
			{
				iso_3166_1: 'US',
				name: 'United States of America',
			},
		],
		release_date: '2016-12-10',
		revenue: 235956898,
		runtime: 127,
		spoken_languages: [
			{
				english_name: 'English',
				iso_639_1: 'en',
				name: 'English',
			},
		],
		status: 'Released',
		tagline:
			'Genie kennt keine Herkunft. Stärke kein Geschlecht. Mut keine Grenzen.',
		title: 'Hidden Figures - Unerkannte Heldinnen',
		video: false,
		vote_average: 8.057,
		vote_count: 8503,
		similar: {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: '/1K9YJzQ6r5nCrOVrjSnAmji8zLc.jpg',
					genre_ids: [18],
					id: 233,
					original_language: 'en',
					original_title: 'The Wanderers',
					overview:
						'New York, 1963: Die Bronx wird von Bandenkriegen erschüttert. Besonders hart sind die Machtkämpfe zwischen den “Baldies” und den “Wanderers”, einer Gruppe italienischer Einwanderersöhne, die vom charismatischen Richie angeführt wird. Damit nicht genug, müssen sich die Jungs mit den alltäglichen Problemen des Erwachsenwerdens und ihren ersten Erfahrungen in Sachen Liebe herumschlagen. Während eines Football-Spiels werden die “Wanderers” von den brutalen “Ducky Boys” herausgefordert. Ein gnadenloser Kampf um die Vorherrschaft in der Bronx beginnt.',
					popularity: 11.773,
					poster_path: '/it7rlmEH1W3SVDNv6XdPG3vpkHH.jpg',
					release_date: '1979-07-13',
					title: 'The Wanderers - Terror in der Bronx',
					video: false,
					vote_average: 7,
					vote_count: 160,
				},
				{
					adult: false,
					backdrop_path: '/kmYVtq3uNQNrveVMuGmO8o4De05.jpg',
					genre_ids: [18],
					id: 403,
					original_language: 'en',
					original_title: 'Driving Miss Daisy',
					overview:
						'Nachdem Miss Daisy, eine reiche jüdische alte Dame in den Südstaaten der USA, ihren wunderschönen Wagen fast zu Schrott gefahren hat, besorgt ihr Sohn ihr einen Chauffeur. Doch die 72jährige will sich nicht an den Gedanken gewöhnen, künftig nur noch mit dem schwarzen Hoke am Steuer Autofahrten zu unternehmen. Nachdem sie ihn zunächst ignoriert, dann wissentlich zu Unrecht des Diebstahls verdächtigt hat, entspinnt sich zwischen den beiden äußerlich wie innerlich so unterschiedlichen Menschen eine 25 Jahre währende, ungewöhnliche Freundschaft, die von gegenseitiger Toleranz und von Verständnis getragen wird.',
					popularity: 14.538,
					poster_path: '/z5XF5aSkL5URyIwemyvWy1vuR03.jpg',
					release_date: '1989-12-13',
					title: 'Miss Daisy und ihr Chauffeur',
					video: false,
					vote_average: 7.2,
					vote_count: 1347,
				},
				{
					adult: false,
					backdrop_path: '/1S81PpyGwS8eVx4W75uSKzMw4B0.jpg',
					genre_ids: [18],
					id: 404,
					original_language: 'en',
					original_title: 'The Straight Story',
					overview:
						'Nachdem sein Bruder, mit dem er seit 10 Jahren zerstritten ist, einen Schlaganfall erlitten hat, beschließt der 73-jährige Alvin Straight, ihn zu besuchen. Da er aber keinen Führerschein besitzt und auch kein Bus fährt, entscheidet sich Alvin, die über 500 km mit dem Rasenmäher zu fahren. Verfilmung einer wahren Geschichte durch Kult-Regisseur David Lynch.',
					popularity: 10.575,
					poster_path: '/zZeeEoKoZsfoIXfGKsUQ44z1rc.jpg',
					release_date: '1999-10-15',
					title: 'The Straight Story - Eine wahre Geschichte',
					video: false,
					vote_average: 7.736,
					vote_count: 1269,
				},
				{
					adult: false,
					backdrop_path: '/viGCwLxupyoaLsa6hrnu1gYrB0B.jpg',
					genre_ids: [18],
					id: 406,
					original_language: 'fr',
					original_title: 'La Haine',
					overview:
						'In den tristen Sozialbausiedlungen der Pariser Vororte brechen Unruhen aus, nachdem ein 16-jähriger Araber von der Polizei fast zu Tode geprügelt wurde. Nach einer Nacht voller Gewalt zwischen Jugendlichen und der Polizei herrscht Ausnahmezustand. Getrieben von Hass gegen das System stehen die Freunde Hubert, Saïd und Vinz an vorderster Front, an einem Tag, der ihr Leben verändern wird.',
					popularity: 18.506,
					poster_path: '/fELddFByKiXwde9vdjb8mejj6xO.jpg',
					release_date: '1995-05-31',
					title: 'Hass',
					video: false,
					vote_average: 8.068,
					vote_count: 3372,
				},
				{
					adult: false,
					backdrop_path: '/dVr11o9or7AS8AMPfwjSpEU83iU.jpg',
					genre_ids: [18, 10752],
					id: 423,
					original_language: 'en',
					original_title: 'The Pianist',
					overview:
						'Warschau, 1939. Die Besetzung Polens durch die Deutschen bedeutet für den gefeierten polnisch-jüdischen Pianisten Wladyslaw Szpilman den Beginn eines langen Leidenswegs. Durch einen Glücksfall entgeht er dem Transport ins KZ, in dem seine gesamte Familie ums Leben kommt. Von nun an fristet er ein Dasein im Untergrund. Hungrig, krank und psychisch vor dem Kollaps stehend, wird er gegen Kriegsende schließlich von einem deutschen Offizier aufgespürt. Doch anstatt ihn auszuliefern, bittet er ihn, Klavier zu spielen. Szpilmans Rettung.  Der Pianist ist eine Filmadaption der Biographie „Das wunderbare Überleben“ von Wladyslaw Szpilman. Das Filmdrama des Regisseurs Roman Polanski hat mit dem Film auch ein Stück eigene Geschichte aufgearbeitet.',
					popularity: 42.825,
					poster_path: '/zdP0WPE5xitsFNztWfj658SIcFS.jpg',
					release_date: '2002-09-17',
					title: 'Der Pianist',
					video: false,
					vote_average: 8.383,
					vote_count: 7928,
				},
				{
					adult: false,
					backdrop_path: '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
					genre_ids: [18, 36, 10752],
					id: 424,
					original_language: 'en',
					original_title: "Schindler's List",
					overview:
						'Von einer wahren Begebenheit inspiriert, erzählt Schindlers Liste die Geschichte des Industriellen Oskar Schindler, der während des Zweiten Weltkriegs versucht, sich in Krakau eine Existenz aufzubauen. Aus finanziellen Gründen beschäftigt er nur Juden und leiht sich Geld von ihnen um eine Emaillefabrik zu gründen, die ihm letztlich großen Reichtum beschert. Als die Brutalität des Holocaust Krakau erreicht, riskiert er nicht nur sein Vermögen, sondern auch sein Leben um seine Arbeiter vor der Deportation zu bewahren.',
					popularity: 50.098,
					poster_path: '/6lzgetyAEL6rKzeac7r9X7lRVkA.jpg',
					release_date: '1993-12-15',
					title: 'Schindlers Liste',
					video: false,
					vote_average: 8.568,
					vote_count: 13886,
				},
				{
					adult: false,
					backdrop_path: '/fXJhA3pjLMDkHPgZ2GVhRDXA5M3.jpg',
					genre_ids: [28, 12, 878, 53],
					id: 435,
					original_language: 'en',
					original_title: 'The Day After Tomorrow',
					overview:
						'Lange prognostiziert, setzen sie plötzlich innerhalb kürzester Zeit weltweit ein, gewaltige Naturereignisse, die eine neue Eiszeit einläuten: Hagelstürme in Tokio, Schneefälle in Indien, Tornados über Los Angeles. Endlich reagiert auch die Regierung und evakuiert alle US-Bürger der südlichen Staaten nach Mexiko, während man mangels Zeit alle anderen dem sicheren Kältetod überlässt. Einzig Klimaforscher Jack Hall kämpft sich durch Blitzeis und Schnee nach Norden, denn sein Sohn sitzt in der New Yorker Bibliothek fest.',
					popularity: 29.084,
					poster_path: '/bnp4hnodAhllZkqCIAhVR5zhHMa.jpg',
					release_date: '2004-05-26',
					title: 'The Day After Tomorrow',
					video: false,
					vote_average: 6.496,
					vote_count: 7109,
				},
				{
					adult: false,
					backdrop_path: '/erA8i1SvSfq3f6he4cGucsqJR9E.jpg',
					genre_ids: [9648, 878, 53],
					id: 438,
					original_language: 'en',
					original_title: 'Cube Zero',
					overview:
						'Irgendwo tief unter der Erde Nordamerikas befindet sich ein riesiger geheimer Komplex, in dem sich, so glaubt es zumindest das Personal, zum Tode verurteilte Straftäter freiwillig einem Versuchsprogramm unterziehen. Als jedoch eine junge Mutter in das lebensgefährliche Labyrinth des Cube gerät, beginnt der junge Wartungsingenieur Eric am System zu zweifeln. Zweifel, die ihn alsbald selbst zum Opfer der perfekten Tötungsmaschinerie machen.',
					popularity: 11.01,
					poster_path: '/cx31RUjyim2Bg0YEzbKZZI3imJ9.jpg',
					release_date: '2004-10-10',
					title: 'Cube Zero',
					video: false,
					vote_average: 5.7,
					vote_count: 880,
				},
				{
					adult: false,
					backdrop_path: '/rKs8y5WlXcYX5GCbDkXcXybGteZ.jpg',
					genre_ids: [35, 18, 10749],
					id: 457,
					original_language: 'de',
					original_title: 'Sissi',
					overview:
						'Der österreichische Kaiser Franz Joseph ist verliebt. Jedoch nicht in Prinzessin Nené, die seine Mutter Erzherzogin Sophie für ihn als zukünftige Kaiserin Österreichs ausgesucht hat. Sissi, die jüngere Schwester von Nené ist das Mädchen, dem er sein Herz schenken will. Franz Joseph ist hingerissen von ihrer Anmut und Schönheit. Sissi will aber dem Glück von Nené nicht im Wege stehen und möchte sich zurückziehen.Aber der junge Kaiser verkündet kurzentschlossen bei einem großen Empfang seine Verlobung mit Sissi - zum Entsetzen seiner Mutter. Bald reist Sissi über die Donau in ihre zukünftige Heimat Österreich. Die Wiener lieben ihre neue Prinzessin, und sie bereiten ihr zur Hochzeit einen prächtigen Empfang.',
					popularity: 15.339,
					poster_path: '/bSTAMc2Hwdb2Gxg3a0UgRU3M7GG.jpg',
					release_date: '1955-12-22',
					title: 'Sissi',
					video: false,
					vote_average: 7.363,
					vote_count: 415,
				},
				{
					adult: false,
					backdrop_path: '/AcGg5H2R5YHDISU6QHlS8xozlYc.jpg',
					genre_ids: [10749, 18, 36],
					id: 459,
					original_language: 'de',
					original_title: 'Sissi - Schicksalsjahre einer Kaiserin',
					overview:
						'Nachdem Sissi inzwischen auch zur Kaiserin von Ungarn gekrönt wurde und das ungarische Volk ihr zu Füssen liegt, scheint alles eitel Sonnenschein. Bei Hofe sagt man Sissi eine Liaison mit dem ungarischen Grafen Andrassy nach. Da ist zwar nichts dran, aber es trübt ihr Verhältnis zu Franz Josef  immerhin so sehr, dass sie junge Kaiserin eine Zeitlang zurück zu ihrer Mutter zieht. Hinzu kommt ein Lungenleiden, das sie zu längeren Auslandsaufenthalten zwingt...',
					popularity: 13.497,
					poster_path: '/ebapwBSGPdaFSLe7SBPPQcFc7p3.jpg',
					release_date: '1957-12-18',
					title: 'Sissi - Schicksalsjahre einer Kaiserin',
					video: false,
					vote_average: 7.193,
					vote_count: 288,
				},
				{
					adult: false,
					backdrop_path: '/3HmLKhahTxX2ALTWlagr92pZrU7.jpg',
					genre_ids: [18],
					id: 462,
					original_language: 'en',
					original_title: 'Erin Brockovich',
					overview:
						'Erin Brockovich ist eine alleinstehende Mutter mit Kindern, die verzweifelt einen Job sucht, ohne daß man ihr eine Chance gibt. Eine Wende deutet sich an, als ihr Anwalt ihren Prozeß wegen eines Autounfalls versiebt. Frustriert zwingt sie ihn, ihr eine Stelle als Sekretärin zu geben, wo sie wegen ihrer aufreizenden Kleidung und ihres resoluten Mundwerks nicht gern gesehen ist. Als sie jedoch einen Fall bearbeitet, in dem die Pacific Gas + Electric Co. heimlich, still und leise Land zurückkauft, findet sie heraus, daß die Firma das Land vor Jahren mit lebensbedrohlichem Chrom kontaminiert hat. Sie bohrt weiter, und obwohl der daraus resultierende Fall eine Klasse zu hoch für ihre kleine Anwaltsfirma ist, treibt sie ihren Chef weiter in die größte Schadensersatzklage aller Zeiten...',
					popularity: 20.271,
					poster_path: '/azYI0dYDbT7JTMBXdMfdpFA9eDH.jpg',
					release_date: '2000-03-17',
					title: 'Erin Brockovich',
					video: false,
					vote_average: 7.418,
					vote_count: 2708,
				},
				{
					adult: false,
					backdrop_path: '/rYpGznw5UExo3ojqRK8eRIfqoEJ.jpg',
					genre_ids: [9648, 18, 53],
					id: 473,
					original_language: 'en',
					original_title: 'Pi',
					overview:
						'Mathematikgenie Max Cohen steht kurz vor der Entschlüsselung eines numerischen Systems, das die Struktur von Zufall und Chaos aufdecken könnte. Mit diesem Code ließen sich nicht nur die Abläufe des Universums erklären, sondern auch Börsenbewegungen voraussagen. Bald sieht sich Max durch skrupellose Wall-Street-Haie verfolgt, aber auch eine religiöse Sekte und der Geheimdienst sind ihm auf den Fersen. Seine mentale Gesundheit leidet, er schlingert mehr und mehr in den Wahnsinn. Als es ihm gelingt, den 216-stelligen Code zu knacken, macht er eine Entdeckung, für die alle bereit sind, ihn zu töten...',
					popularity: 15.262,
					poster_path: '/mJsvzn2mbJPXNXKUdsgwB1WwLbX.jpg',
					release_date: '1998-07-10',
					title: 'Pi - Der Film',
					video: false,
					vote_average: 7.118,
					vote_count: 1919,
				},
				{
					adult: false,
					backdrop_path: '/vXhTr0cN54R0TbSD9iG5cuAEWcT.jpg',
					genre_ids: [28, 18, 36, 10752],
					id: 197,
					original_language: 'en',
					original_title: 'Braveheart',
					overview:
						'Ende des 13. Jahrhunderts ermorden britische Besatzer die geliebte Frau des in Schottland lebenden William Wallace. Von dieser Tat aufgestachelt und blind vor Rache, mobilisiert er seine schottischen Landleute für einen Feldzug gegen die übermächtigen Engländer. Trotz ihrer nicht nur zahlenmäßigen Unterlegenheit schafft man das Unfassbare und besiegt die Armee des britischen Königs. Nach dem Sieg stehen jedoch nicht alle Schotten hinter Wallace und verraten ihren Freiheitskämpfer.',
					popularity: 48.824,
					poster_path: '/5MiqFuwgBrvIF3KJ6nWaqUeAe52.jpg',
					release_date: '1995-05-24',
					title: 'Braveheart',
					video: false,
					vote_average: 7.932,
					vote_count: 8983,
				},
				{
					adult: false,
					backdrop_path: '/tGhWuZp1fdM0mftTWv88nxgkBUl.jpg',
					genre_ids: [18, 53, 9648, 10749],
					id: 1049,
					original_language: 'en',
					original_title: 'Sommersby',
					overview:
						'1867: Nach siebenjähriger Abwesenheit kehrt Jack Sommersby aus dem Bürgerkrieg als gewandelter Mann nach Hause zurück. Tat er sich früher als gewaltbereiter Rowdy hervor, ist er nun ein liebender Ehemann und blühendes Vorbild, der das Dorf mit der Idee, Tabak anzupflanzen, vor dem Untergang retten will. Erste Zweifel an seiner Identität kommen auf. Dann wird Jack Sommersby wegen Mordes verhaftet. Seine Frau Laurel will ihn retten, denn sie weiß, daß er in Wirklichkeit nicht Jack ist.',
					popularity: 10.176,
					poster_path: '/tAgQKLv0GK97Tr0bvdI66oXlEVb.jpg',
					release_date: '1993-02-05',
					title: 'Sommersby',
					video: false,
					vote_average: 6.35,
					vote_count: 314,
				},
				{
					adult: false,
					backdrop_path: '/8gDHMslJaqDWJInDQBfX4pwwEOh.jpg',
					genre_ids: [12, 36, 28],
					id: 1911,
					original_language: 'en',
					original_title: 'The 13th Warrior',
					overview:
						'Bagdad 922 : Der arabische Edelmann Ahmed Ibn Fahdlan wird wegen einer Affäre mit einer verheirateten Frau des Landes verwiesen. Auf Geheiß des Kalifen muss er fortan die unbekannten und sagenumwobenen nordischen Länder erkunden. Auf seiner Reise stößt er auf eine Gruppe barbarischer Wikinger, die sich als Söldner verdingen und vom hünenhaften Krieger Buliwyf geführt werden. Der Sohn des nordischen Königs Hrothgar erbittet Hilfe für eine lebensgefährliche Mission: das Reich seines Vaters muss gegen übernatürliche, blutrünstige und scheinbar unbezwingbare Kreaturen verteidigt werden, die aus nebligen Mooren wie ein flammender Drache emporsteigen und alle Männer des Landes massakrieren. Die Seherin der Wikinger besagt, dass nur 13 auserwählte Krieger die unheimlichen Horden besiegen können. Sie sieht in Ibn Fahdlan den vom Schicksal gesandten 13ten Krieger.',
					popularity: 21.394,
					poster_path: '/mPNF8rFlqfM1ubRtMHXYGhHJQ10.jpg',
					release_date: '1999-08-13',
					title: 'Der 13te Krieger',
					video: false,
					vote_average: 6.656,
					vote_count: 1572,
				},
				{
					adult: false,
					backdrop_path: '/7XmDhCTkce5GH8KCdbMoTZdxn1p.jpg',
					genre_ids: [18],
					id: 1913,
					original_language: 'es',
					original_title: 'Mar adentro',
					overview:
						'In seinen Gedanken ist Ramón immer noch jung, agil und bei den Frauen beliebt. Doch die Realität ist bitter, ist der hochintelligente Mann doch seit einem Badeunfall vor 27 Jahren vom Hals abwärts gelähmt. Schon lange will er sich freiwillig aus diesem Dasein verabschieden. Doch dazu würde er Hilfe brauchen - und die versagen ihm Staat und Kirche; und sogar der eigene Bruder, in dessen Haus er lebt, aufopferungsvoll gepflegt von seiner Schwägerin. Erst das Auftauchen der lebenslustigen Rosa lässt seinen Wunsch in greifbare Nähe rücken.',
					popularity: 10.476,
					poster_path: '/d3EdEtpCXKgRkehHxQCK06oLNkD.jpg',
					release_date: '2004-09-03',
					title: 'Das Meer in mir',
					video: false,
					vote_average: 7.582,
					vote_count: 784,
				},
				{
					adult: false,
					backdrop_path: '/kYd1ZMWvG9K2Jeop3XWXcTpJ2dB.jpg',
					genre_ids: [878, 28],
					id: 1927,
					original_language: 'en',
					original_title: 'Hulk',
					overview:
						'Der Forscher Dr. Bruce Banner mutiert als Folge eines fehlgeschlagenen Experiments zum zerstörerischen grünen Muskelberg, sobald er wütend wird. Während Kollegin Betty, mit der ihn mehr als nur die Arbeit verbindet, zu dem vermeintlichen Monster hält, hat der Hulk auch viele Feinde. Beispielsweise den fiesen Wissenschaftler Glenn Talbot, der die "Kampfmaschine" militärisch "nützen" will, General Ross, der sie "ausschalten" möchte, und natürlich Vater David, der Schuld daran trägt, dass Bruce zum Ungetüm wurde.',
					popularity: 42.009,
					poster_path: '/6NdjC4Ke3clvslxx8DfaAytwcbH.jpg',
					release_date: '2003-06-19',
					title: 'Hulk',
					video: false,
					vote_average: 5.527,
					vote_count: 5182,
				},
				{
					adult: false,
					backdrop_path: '/jP2htGBHE7vKq4MLeC75UeC0sZH.jpg',
					genre_ids: [80, 18, 9648, 53],
					id: 1949,
					original_language: 'en',
					original_title: 'Zodiac',
					overview:
						'In der sonnigen Bay Area San Franciscos beginnt 1968 eine grausame Mordserie. Der unbekannte Killer lauert verliebten Pärchen auf und bringt sie um. Anschließend führt er Polizei und Presse mit kryptischen Briefen, in denen er sich Zodiac nennt und seiner Untaten brüstet, an der Nase herum. Zeitungsreporter und Fahnder aus vier Distrikten suchen nach dem Mörder. Als ein Teenager seine Attacken überlebt und ihn als weiß Maskierten beschreibt, bricht Panik in der Stadt aus. Der unlösbare Fall wird bald zur Obsession für die vier Detectives.',
					popularity: 38.226,
					poster_path: '/5tnuz3iLfeK7PJ8NK8OsnEOoczf.jpg',
					release_date: '2007-03-02',
					title: 'Zodiac - Die Spur des Killers',
					video: false,
					vote_average: 7.514,
					vote_count: 9124,
				},
				{
					adult: false,
					backdrop_path: '/hKpzq3U7X1C1lqnYh0WQwlPyxO5.jpg',
					genre_ids: [18, 36],
					id: 1955,
					original_language: 'en',
					original_title: 'The Elephant Man',
					overview:
						'Seit seiner Kindheit ist John Merrick furchtbar entstellt. Als "Elefantenmensch" wird er auf Jahrmärkten vorgeführt und von seinem sadistischen "Besitzer" gequält, bis ihn schließlich der Arzt Frederick Treves entdeckt und ihm Hilfe anbietet. John Merrick soll endlich wie ein Mensch leben. David Lynchs zweiter Spielfilm ist ein eindringliches Plädoyer für Menschlichkeit und Würde. Die meisterliche Schwarzweißfotografie von Kameramann Freddie Francis und das bemerkenswerte Spiel von John Hurt und Anthony Hopkins ließen den Film zu einem gefeierten Klassiker werden.',
					popularity: 22.153,
					poster_path: '/8tP1LiHH9TbzrWhpDxnNxQf9103.jpg',
					release_date: '1980-10-09',
					title: 'Der Elefantenmensch',
					video: false,
					vote_average: 8.057,
					vote_count: 2971,
				},
				{
					adult: false,
					backdrop_path: '/qykc21PjbISZCmpKedY76fojV1I.jpg',
					genre_ids: [10749, 18],
					id: 1967,
					original_language: 'en',
					original_title: 'Ask the Dust',
					overview:
						'Der italienischstämmige Arturo Bandini ist während der großen Depression von Colorado nach Los Angeles gezogen, um seiner Familie und seinen Freunden zu beweisen, dass er es als Schriftsteller schaffen kann. In einer schäbigen Bar lernt er die feurige Mexikanerin Camilla kennen, die seine Gefühle nur bedingt erwidert. Sie verliebt sich in einen weißen Barmann – und schließlich in harte Drogen, die ihren Niedergang bedeuten. Erst als er sich von Camilla frei machen kann, platzt bei Bandini der kreative Knoten.',
					popularity: 9.55,
					poster_path: '/iuJZyJNiQxnmMBBqu40mF0a2nuv.jpg',
					release_date: '2006-02-02',
					title: 'In den Staub geschrieben',
					video: false,
					vote_average: 5.301,
					vote_count: 123,
				},
			],
			total_pages: 277,
			total_results: 5521,
		},
	},
	{
		adult: false,
		backdrop_path: '/1vXD5HXqkhvsXFHE7KmCPZGPR1e.jpg',
		belongs_to_collection: null,
		budget: 0,
		genres: [
			{
				id: 18,
				name: 'Drama',
			},
			{
				id: 35,
				name: 'Comedy',
			},
		],
		homepage: 'https://searchlightpictures.com/films/the-banshees-of-inisherin',
		id: 674324,
		imdb_id: 'tt11813216',
		original_language: 'en',
		original_title: 'The Banshees of Inisherin',
		overview:
			'Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.',
		popularity: 100.89,
		poster_path: '/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg',
		production_companies: [
			{
				id: 127929,
				logo_path: '/fCB4AVYvxxDvqumgYqsN6ehyN3G.png',
				name: 'Searchlight Pictures',
				origin_country: 'US',
			},
			{
				id: 2376,
				logo_path: '/yeNoWmSHZfvKsBYuL8uTRE4LPdQ.png',
				name: 'Blueprint Pictures',
				origin_country: 'GB',
			},
			{
				id: 6705,
				logo_path: '/e8EXNSfwr5E9d3TR8dHKbQnQK4W.png',
				name: 'Film4 Productions',
				origin_country: 'GB',
			},
			{
				id: 86504,
				logo_path: '/7ppNVcvDg0ZXSR1bZi397hLD206.png',
				name: 'Metropolitan Films International',
				origin_country: 'IE',
			},
			{
				id: 22213,
				logo_path: '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
				name: 'TSG Entertainment',
				origin_country: 'US',
			},
		],
		production_countries: [
			{
				iso_3166_1: 'IE',
				name: 'Ireland',
			},
			{
				iso_3166_1: 'GB',
				name: 'United Kingdom',
			},
		],
		release_date: '2022-10-20',
		revenue: 41000000,
		runtime: 114,
		spoken_languages: [
			{
				english_name: 'English',
				iso_639_1: 'en',
				name: 'English',
			},
		],
		status: 'Released',
		tagline: 'Everything was fine yesterday.',
		title: 'The Banshees of Inisherin',
		video: false,
		vote_average: 7.539,
		vote_count: 1437,
		similar: {
			page: 1,
			results: [
				{
					adult: false,
					backdrop_path: '/oKNe6Ids29lqvG6PFc4qxlB3j1R.jpg',
					genre_ids: [18],
					id: 10397,
					original_language: 'en',
					original_title: "Angela's Ashes",
					overview:
						'Brooklyn, im Jahre 1934: Da das Familienglück der McCords in Amerika ausbleibt, verschlägt es sie zurück in ihre irische Heimat nach Limerick. Doch dort angekommen erwartet sie nur bittere Armut und Trostlosigkeit. So gibt auch der Arbeitsmarkt keine Stelle für den jungen Familienvater Malachy her, was ihn und seine Familie allmählich in die Verzweiflung treibt. Seinen Frust ertränkt er schließlich im Alkohol, während seine Kinder kaum etwas zu essen haben und mit lumpigen Kleidern zur Schule gehen müssen. Auch der kleine Franky leidet zunehmend unter den streng katholischen Sitten des Landes und der Alkoholsucht seines Vaters. Zusammen mit seinen Schulfreunden versucht er dennoch das Beste aus seinem Leben zu machen, vergnügt sich im städtischen Kino und lernt seine erste Liebe kennen. Doch für Frank steht fest, dass er eines Tages alles hinter sich lassen möchte um irgendwann nach Amerika zurückkehren.',
					popularity: 8.699,
					poster_path: '/pDx64U22b64iJy1pYZsgubcuS8O.jpg',
					release_date: '1999-12-25',
					title: 'Die Asche meiner Mutter',
					video: false,
					vote_average: 7.236,
					vote_count: 246,
				},
				{
					adult: false,
					backdrop_path: '/anSbunnEMI0TSmizqUSRACoe18l.jpg',
					genre_ids: [28, 27, 878],
					id: 10016,
					original_language: 'en',
					original_title: 'Ghosts of Mars',
					overview:
						'Der Mars im Jahre 2176: Mehr als 640.000 Menschen haben die überbevölkerte Erde verlassen und leben mittlerweile in versprengten Siedlungen auf dem roten Planeten. Dort werden in unzähligen Minen die wertvollen Bodenschätze abgetragen. Doch in Shining Canyon ereignet sich bei einer dieser Operationen ein verheerender Zwischenfall: Eine lange verschwundene Ur-Zivilisation des Mars wird zu neuem Leben erweckt - und beginnt einen unbarmherzigen Feldzug gegen die menschlichen Einwanderer. Commander Helena Braddock und ihr Team gehören zu denjenigen, die sich den bösen Kräften erwehren müssen. Eigentlich sollten sie nur den Schwerverbrecher Desolation Williams abholen, aber nun kämpfen sie mit von Geistern besessenen Mienenarbeitern.',
					popularity: 15.67,
					poster_path: '/bZsMqPnlOBsSzNhre0j01U4cWXQ.jpg',
					release_date: '2001-08-24',
					title: 'Ghosts of Mars',
					video: false,
					vote_average: 5.157,
					vote_count: 927,
				},
				{
					adult: false,
					backdrop_path: '/dgp3j52f2MeNVrp7PY8A1pCtRZT.jpg',
					genre_ids: [35, 18],
					id: 8221,
					original_language: 'es',
					original_title: '¿Qué he hecho yo para merecer esto!',
					overview:
						'Wenn Gloria von diversen Putzjobs in ihre winzige Wohnung am hässlichen Stadtrand Madrids zurückkehrt, wartet dort schon wieder ein Berg von Arbeit auf sie: kochen, putzen, waschen, bügeln, tagaus, tagein. Und das Geld ist auch immer knapp. Freuden gibt es in Glorias Alltag keine. Ihre Sippschaft gibt dafür auch, weiß Gott, wenig Anlass. Als der tablettensüchtigen Gloria eines Tages dann auch noch die Appetitzügler ausgehen, beginnen ihre Neren zu vibrieren: Es kommt zur Katastrophe.',
					popularity: 6.195,
					poster_path: '/9ZzQLDfjlkxZryqJpSnD4m8K3Ed.jpg',
					release_date: '1984-10-25',
					title: 'Womit habe ich das verdient?',
					video: false,
					vote_average: 7.301,
					vote_count: 178,
				},
				{
					adult: false,
					backdrop_path: '/bWukUgej8vZTRF9YFi2NWmswZie.jpg',
					genre_ids: [10749, 35, 18, 27],
					id: 10288,
					original_language: 'en',
					original_title: 'Fido',
					overview:
						'Zombies, die einst im Krieg gegen die Menschheit standen, können nun mithilfe eines elektronischen Halsbands gezähmt und als Arbeitskraft genutzt werden. Die Firma ZomCom macht’s möglich. Zombies werden zum Statussymbol und auch in der idyllischen 50er-Jahre-Kleinstadt Willard will jeder einen haben. Der Zombie der Robinsons heißt Fido. Dumm nur, dass Mr. Robinson aufgrund traumatischer Kriegserlebnisse Angst vor Zombies hat und der eigentlich so liebenswerte Fido durch einen Ausfall seines Halsbands eine Nachbarin frisst …',
					popularity: 10.376,
					poster_path: '/5XPSkAsapPPS5m6ReSdvNz0kbdl.jpg',
					release_date: '2006-09-07',
					title: 'Fido - Gute Tote sind schwer zu finden',
					video: false,
					vote_average: 6.5,
					vote_count: 379,
				},
				{
					adult: false,
					backdrop_path: '/b3J5vJWbyfbjPtgWKfCJYQ8kves.jpg',
					genre_ids: [80, 35, 10749],
					id: 11300,
					original_language: 'en',
					original_title: 'Something Wild',
					overview:
						'Der biedere, aber Abwechslungen nicht abgeneigte Charlie läßt sich auf eine Spritztour mit der exzentrischen Zufallsbekanntschaft Lulu ein. Die verführt ihn und animiert ihn zu kleineren Gesetzesübertretungen. Doch plötzlich gerät Charlie in eine tödliche Auseinandersetzung mit Lulus Ehemann.',
					popularity: 9.81,
					poster_path: '/fxgyfc4N3iZqsNCxQpnUWfao7XJ.jpg',
					release_date: '1986-11-07',
					title: 'Gefährliche Freundin',
					video: false,
					vote_average: 6.553,
					vote_count: 262,
				},
				{
					adult: false,
					backdrop_path: '/kAgCJcSO4kbVRtaMW8YWHiZPHxr.jpg',
					genre_ids: [35, 18, 10749],
					id: 10247,
					original_language: 'en',
					original_title: 'He Was a Quiet Man',
					overview:
						'Bob, ein frustrierter Büroangestellter, träumt jeden Tag davon, seine ignoranten Kollegen zu ermorden - bis dies ein Kollege selbst versucht und Bob den Amokläufer stoppen kann. Aus der grauen Maus wird so ein gefeierter Held, dem auch die attraktive Vanessa nicht widerstehen kann.',
					popularity: 9.681,
					poster_path: '/sL0M9LzjCMb11eeBZhwdvjiwW2Q.jpg',
					release_date: '2007-11-23',
					title: 'Amok - He Was a Quiet Man',
					video: false,
					vote_average: 6.439,
					vote_count: 263,
				},
				{
					adult: false,
					backdrop_path: '/t8uoVAyKzfcvnVpPBpLwXt2nuWh.jpg',
					genre_ids: [35, 80, 53],
					id: 11592,
					original_language: 'en',
					original_title: 'Serial Mom',
					overview:
						'Beverly Sutphin, liebende Ehefrau des Vorstadtzahnarztes Eugene nimmt ihren Mutterinstinkt manchmal etwas zu genau. Den Mathelehrer ihres Sohnes Chip überfährt sie, als dieser eine Therapie für den Splatterfilmfan vorschlägt. Dem untreuen Freund ihrer Tochter Misty rammt sie ein Feuereisen in den Bauch. Auch nörgelnde Nachbarn traktiert sie mit Scheren, Lammkeulen und Klimaanlagen. Schließlich wird die Serial Mom gefaßt und vor Gericht gestellt, kann jedoch in glorioser Selbst-Verteidigung einen Freispruch erwirken.',
					popularity: 10.522,
					poster_path: '/ltcaA95mRq6YwtdTetQOOUsPW2t.jpg',
					release_date: '1994-04-13',
					title: 'Serial Mom - Warum lässt Mama das Morden nicht?',
					video: false,
					vote_average: 6.775,
					vote_count: 566,
				},
				{
					adult: false,
					backdrop_path: '/bQHHEFYBZc23nhbo0z0qB7nxW31.jpg',
					genre_ids: [35, 18, 10402],
					id: 11663,
					original_language: 'en',
					original_title: 'The Commitments',
					overview:
						'Derek und Outspan verdienen sich im grauen Dublin der 80er etwas Geld, in dem sie auf Hochzeiten Musik machen. Sie bitten ihren ebenfalls arbeitslosen Kumpel Jimmy sie zu managen, um richtig Kohle zu verdienen. Der sagt ja, aber zu seinen eigenen Bedingungen. Außer Soul kommt kein Musikstil in Frage und so lädt er per Zeitungsannonce zum Casting ins elterliche Wohnzimmer. Aus unzähligen Bewerbern siebt er nach und nach seine Band aus. Zusammen mit den Backgroundsängerinnen Imelda, Bernie und Natalie, die sehr motivierend auf die Bandmitglieder wirken, beginnen harte Wochen des Probens ...',
					popularity: 10.199,
					poster_path: '/tzVRDThC29cPJYF9IG1D9IrvKs2.jpg',
					release_date: '1991-08-14',
					title: 'Die Commitments',
					video: false,
					vote_average: 7.272,
					vote_count: 456,
				},
				{
					adult: false,
					backdrop_path: '/4HJN6dyyPMJTimMglfEdVxjW2p5.jpg',
					genre_ids: [35, 27, 53],
					id: 11974,
					original_language: 'en',
					original_title: "The 'Burbs",
					overview:
						'Eigentlich hatte Ray Peterson sich seine Urlaubstage im trauten Heim ja anders vorgestellt. Als nebenan neue Nachbarn einziehen, die man tagsüber nie zu Gesicht bekommt, dafür nachts umso unheimlichere Geräusche und Blitze aus dem Nachbarhaus dringen, ist es mit der Ruhe vorbei. Ray beschließt den Neulingen auf die Schliche zu kommen.',
					popularity: 19.124,
					poster_path: '/84ZBVwv2n8eTyYQhRUnV1hSEDHq.jpg',
					release_date: '1989-02-17',
					title: 'Meine teuflischen Nachbarn',
					video: false,
					vote_average: 6.736,
					vote_count: 1026,
				},
				{
					adult: false,
					backdrop_path: '/7sKiDbNkO1kht9HoWX1Vp9ZBlWA.jpg',
					genre_ids: [35, 18, 14],
					id: 11139,
					original_language: 'fr',
					original_title: 'Léolo',
					overview:
						'Leolos Welt ist die der Phantasie. Er verwandelt die Wirklichkeit in Lüge. Er glaubt, daß seine Mutter von einer verseuchten Tomate schwanger war, und der Arzt nicht den Mut hatte, ihr das zu sagen. Er ist auch fest überzeugt davon, daß alle in der Familie vom Großvater eine kleine Zelle zuviel im Gehirn abbekommen haben. Deshalb auch der Psychiater. Seine Familie ist ein einziger Alptraum. Da hilft nur noch die Liebe zu Bianca, der Kleinen aus der Nachbarschaft. Wenn es sein müßte, würde Leolo für sie seine ganze, bescheuerte Familie umbringen.',
					popularity: 5.489,
					poster_path: '/swwuA1fw32seLqUhAD5kQl2D2aN.jpg',
					release_date: '1992-09-16',
					title: 'Léolo',
					video: false,
					vote_average: 7.029,
					vote_count: 104,
				},
				{
					adult: false,
					backdrop_path: '/z62CBlBBBOoNUuuxZ1jMAcq5ARE.jpg',
					genre_ids: [10749, 10751, 16],
					id: 10198,
					original_language: 'en',
					original_title: 'The Princess and the Frog',
					overview:
						'Während Kellnerin Tiana im New Orleans der Jahrhundertwende mit eiserner Disziplin ihren Lebenstraum verfolgt – ein eigenes Restaurant zu eröffnen – taucht der adrette Prinz Naveen in der Jazzmetropole auf. Durch eine Verkettung unglücklicher Umstände und unter tatkräftiger Mithilfe des boshaften Voodoo-Zauberers Dr. Facilier wird aus der charmanten Arbeitsbiene und dem naiven Adligen ein Froschpaar. Auf der Suche nach einem Gegenmittel begeben sich die beiden auf Abenteuerreise in die Sümpfe Louisianas. Begleitet werden sie vom Trompete spielenden Alligator Louis und dessen Sidekick Ray, einem in Liebesdingen versierten Glühwürmchens.',
					popularity: 103.942,
					poster_path: '/dZXs0WK8OklsrMWfx9VPpxZhJpp.jpg',
					release_date: '2009-12-08',
					title: 'Küss den Frosch',
					video: false,
					vote_average: 7.18,
					vote_count: 4829,
				},
				{
					adult: false,
					backdrop_path: '/bbheceIw87Gn7lCD1oqhupE2uWX.jpg',
					genre_ids: [35, 18, 53],
					id: 9894,
					original_language: 'en',
					original_title: 'The Cable Guy',
					overview:
						'Steven Kovacs wurde von seiner Freundin Robin Harris aus seinem Apartment geworfen. Für die Elektrik in seiner neuen Wohnung engagiert er den Kabeltechniker Chip Douglas. Steven gibt vor, sich für die Arbeit des einsamen Chip zu interessieren. Dieser deutet das Interesse als ein Freundschaftsgesuch. Und tatsächlich entwickelt sich zwischen den beiden Männern eine private Bande. Aber Chip leistet sich einen Fehler, als er glaubt die richtige Lösung für Stevens Liebeskummer parat zu haben, der immer noch über die Trennung von seiner Ex-Freundin Robin trauert. Chips eigenmächtiger Plan führt schließlich dazu, dass sich Steven hintergangen fühlt und sich von Chip distanziert. Damit kann Chip aber überhaupt nicht gut umgehen und dreht völlig durch.',
					popularity: 16.249,
					poster_path: '/je5wboEQKtsHEFLAk75m63Adk8O.jpg',
					release_date: '1996-06-10',
					title: 'Cable Guy - Die Nervensäge',
					video: false,
					vote_average: 5.958,
					vote_count: 2065,
				},
				{
					adult: false,
					backdrop_path: '/scrH5AMMD2o73vwgCnhcYXx8zrt.jpg',
					genre_ids: [35, 80, 10749],
					id: 10878,
					original_language: 'en',
					original_title: 'Saving Silverman',
					overview:
						'"Zickenterror", den muss man wohl von der attraktiven und ebenso zickigen wie kaltschnäuzigen Psychologin Judith erwarten. Aber wenn man verliebt ist, sieht man solche Sachen nicht. Und damit Darren, bester Freund von Wayne und J.D., keine Dummheit begeht, schmieden sie einen Plan. Judith, mittlerweile die Verlobte von Darren, wird einfach entführt. Sie darf so lange nicht raus, bis die Freunde Darren anderweitig verkuppelt haben. Er soll wieder mit seiner High-School-Freundin Sandy zusammenkommen - doch es gilt, sich zu beeilen, da Darrens Ex kurz davor steht, in ein Kloster einzutreten. Womit die Kumpels ebenfalls nicht gerechnet haben: die entführte Judith macht ihnen das Leben zur Hölle...',
					popularity: 10.885,
					poster_path: '/13j6uciyHr2zGNjlmjUnmljNTPJ.jpg',
					release_date: '2001-02-09',
					title: 'Zickenterror - Der Teufel ist eine Frau',
					video: false,
					vote_average: 5.5,
					vote_count: 451,
				},
				{
					adult: false,
					backdrop_path: '/8LSl2BPsRmookhO0UITB6PStZJX.jpg',
					genre_ids: [12, 10751, 14],
					id: 10140,
					original_language: 'en',
					original_title:
						'The Chronicles of Narnia: The Voyage of the Dawn Treader',
					overview:
						'Die Geschwister Edmund und Lucy verbringen einen langen, lausigen Sommer bei ihrem unausstehlich besserwisserischen Cousin Eustacius Knilch. Ihre bedauerliche, an Abenteuern arme Lage ändert sich, als sie von einem Gemälde verschlungen und auf das Schiff Morgenröte, dass den Ozean von Narnia druchquert, gespült werden. Dort treffen sie auf alte Bekannte: Ihr blaublütiger Freund Kaspian und die Krieger-Maus Reepicheep warten schon auf sie. Gemeinsam werden sie von dem Löwen Aslan auf eine geheimnissvolle Mission geschickt...',
					popularity: 40.874,
					poster_path: '/acTxrky2zmHt2UOsYWFHJcpIVsu.jpg',
					release_date: '2010-12-02',
					title: 'Die Chroniken von Narnia: Die Reise auf der Morgenröte',
					video: false,
					vote_average: 6.423,
					vote_count: 5013,
				},
				{
					adult: false,
					backdrop_path: '/kQVb0jSg5onP548nzHuSEgwxaLT.jpg',
					genre_ids: [35],
					id: 10162,
					original_language: 'en',
					original_title: 'Waking Ned',
					overview:
						"Jackie O'Shea träumt seit Jahren vom großen Lottogewinn. Doch das Schicksal ist ihm nicht gewogen. Nicht nur, daß es das Glück stets an ihm vorbeiziehen läßt, es erwählt auch noch jemanden aus Jackies unmittelbarer Nachbarschaft - einen der restlichen 51 Einwohner seines Heimatdorfes Tullymore. Doch wer ist es? Jackie und sein Kumpel Michael beginnen sofort mit ihren Nachforschungen. Bald wissen sie, wer der Glückliche ist: Ned Devine. Dumm nur, daß der alte Ned vor lauter Freude über seinen Gewinn einem Herzschlag erlegen ist...",
					popularity: 8.014,
					poster_path: '/8GUlaTFZjTNuh0PzUWlkAJgaKcE.jpg',
					release_date: '1998-09-15',
					title: 'Lang lebe Ned Devine!',
					video: false,
					vote_average: 7.145,
					vote_count: 238,
				},
				{
					adult: false,
					backdrop_path: '/ktvFYpvolLOzUzWV7tXt6Mz0jwH.jpg',
					genre_ids: [35, 10749],
					id: 11141,
					original_language: 'en',
					original_title: 'Laws of Attraction',
					overview:
						'Sie sind zwei der dicksten Fische im Teich der hungrigen Scheidungsanwälte in New York: Daniel Rafferty hat noch nie einen Fall verloren und Audrey Woods  ist heißeste Kandidatin auf die ganz großen Fälle, woraufhin die beiden vor Gericht sich immer die Köpfe einrennen. Ein geplantes Businessmeeting samt Abendessen endet für beide schließlich mit einem gemeinsam verbrachten Nacht, aber noch lange nicht mit einer Beziehung. Denn es steht ein Scheidungsfall mit riesigem Potential an, als sich Rockstar Thorne Jamison von seiner Frau und Designerin Selena scheiden lassen will. Prompt landen die Klienten bei den beiden und vor Gericht bleibt es natürlich nicht beim beruflichen Zwist...',
					popularity: 11.092,
					poster_path: '/6aqR0xwmK0mPOIVShDlT88Vo5W0.jpg',
					release_date: '2004-04-04',
					title: 'Laws of Attraction',
					video: false,
					vote_average: 5.7,
					vote_count: 363,
				},
				{
					adult: false,
					backdrop_path: '/jRFC2W21pWAwKUqbEmvG5mVbcle.jpg',
					genre_ids: [35, 80, 18],
					id: 10872,
					original_language: 'en',
					original_title: 'The Ref',
					overview:
						'Der Einbrecher Gus bricht am Heiligen Abend in ein Haus ein und wird dabei von den Bewohnern überrascht, die er kurzerhand zur Geisel nimmt. Leider stellt sich heraus, dass sie sich im Ehestreit befindet, was die ganze Angelegenheit verkompliziert.',
					popularity: 7.619,
					poster_path: '/pf27WgCZJy1oGuxTW7ClIsbBftA.jpg',
					release_date: '1994-03-09',
					title: 'No Panic - Gute Geiseln sind selten',
					video: false,
					vote_average: 6.506,
					vote_count: 272,
				},
				{
					adult: false,
					backdrop_path: '/yB5n2EfRkQfTFpYL2yCX7eJLAUk.jpg',
					genre_ids: [28, 12, 35, 53],
					id: 9448,
					original_language: 'en',
					original_title: 'The Big Hit',
					overview:
						'Profikiller Melvin Smiley hat nach getaner Arbeit gerne seine Ruhe. Leider neigen sowohl Pam, die Verlobte, als auch Chantel, die Geliebte, zu zänkischen Auseinandersetzungen. Die Probleme mehren sich, als Melvin herausfindet, daß sein jüngstes Entführungsopfer nicht nur die Tochter eines reichen Japaners, sondern auch das Patenkind seines Chefs ist. Der beauftragt ausgerechnet Melvin und seine Kumpane, mit den Kidnappern kurzen Prozeß zu machen. Und dann kommen auch noch Melvins zukünftige Schwiegereltern überraschend zu Besuch.',
					popularity: 14.659,
					poster_path: '/3rpSU0sh7kbQgV8IEL6sKNiMv7.jpg',
					release_date: '1998-04-24',
					title: 'The Big Hit',
					video: false,
					vote_average: 5.9,
					vote_count: 349,
				},
				{
					adult: false,
					backdrop_path: '/AnWx27hbrHlx9EafxEAj5Iifyjx.jpg',
					genre_ids: [35, 10749],
					id: 9451,
					original_language: 'en',
					original_title: 'Election',
					overview:
						'Tracy Flick hat sich das Amt der Schulsprecherin in den Kopf gesetzt. Angesichts ihrer aufgesetzten Tugendhaftigkeit bekommt der beliebte Lehrer Mr. McAllister das kalte Grausen und mobilisiert den gutmütigen Football-Jock Paul als Gegenkandidat. Es beginnt eine heiße Wahlkampagne, bei der McAllister in ein tiefes Fettnäpfchen tritt.',
					popularity: 13.236,
					poster_path: '/5gPOFU6IPvDrx50XaPCK4twNw79.jpg',
					release_date: '1999-04-23',
					title: 'Election',
					video: false,
					vote_average: 6.831,
					vote_count: 866,
				},
				{
					adult: false,
					backdrop_path: '/7WBNrwjHrt3YTIbn5vWAJLf9yKD.jpg',
					genre_ids: [28, 35, 27, 80, 14],
					id: 10722,
					original_language: 'es',
					original_title: 'El día de la bestia',
					overview:
						'Professor Angel Berriartua hat seit 25 Jahren die Bücher der Apokalypse studiert. Er ist zu der Überzeugung gelangt, dass der Antichrist am Weihnachtsabend in Madrid geboren wird und die Menschheit fortan in ewiger Verdammnis leben muss. Dadurch, dass er böse Taten begeht und dabei skurrile Verhaltensweisen an den Tag legt, hofft er, den Teufel heraufbeschwören zu können, um ihn dann zu überlisten. Es gelingt ihm, in dem Death Metal-Freak Jose Maria und in dem betrügerischen Fernsehprediger Cavan Mitstreiter für seine Sache zu gewinnen. Zusammen geraten sie in die absurdesten Situationen, bis es in einem apokalyptischen Showdown zur Konfrontation mit dem Teufel kommt.',
					popularity: 7.701,
					poster_path: '/swn86qlIdAvUOnwrOMNEWOTt27a.jpg',
					release_date: '1995-10-20',
					title: 'El día de la bestia',
					video: false,
					vote_average: 7.3,
					vote_count: 440,
				},
			],
			total_pages: 82,
			total_results: 1630,
		},
	},
];
